global:
  resolve_timeout: 1m

route:
  receiver: "gmail-notifications"

receivers:
  - name: "gmail-notifications"
    email_configs:
      - to: "" # receiver email
        from: "" # sender(monitoring system) gmail
        smarthost: "smtp.gmail.com:587"
        auth_username: "" # sender(monitoring system) gmail
        auth_identity: "" # sender(monitoring system) gmail
        auth_password: "" # sender(monitoring system) gmail's app password https://support.google.com/mail/answer/185833?hl=en
        send_resolved: true
