[package]
name = "bifrost-testnet-runtime"
version = "1.0.0"
description = "The runtime for Bifrost testnet"
authors = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# third-party dependencies
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
hex-literal = { workspace = true, optional = true }
rlp = { workspace = true, optional = true }
sha3 = { workspace = true, optional = true }
num_enum = { workspace = true }

# Bifrost
bifrost-common-runtime = { workspace = true }
bifrost-testnet-constants = { workspace = true }
bp-core = { workspace = true }
precompile-utils = { workspace = true }

# FRAME dependencies
frame-system = { workspace = true }
frame-support = { workspace = true }
frame-executive = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-system-benchmarking = { workspace = true, optional = true }
pallet-aura = { workspace = true }
pallet-balances = { workspace = true, features = ["insecure_zero_ed"] }
pallet-grandpa = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-session = { workspace = true, features = ["historical"] }
pallet-authorship = { workspace = true }
pallet-utility = { workspace = true }
pallet-collective = { workspace = true }
pallet-democracy = { workspace = true }
pallet-membership = { workspace = true }
pallet-im-online = { workspace = true }
pallet-offences = { workspace = true }
pallet-treasury = { workspace = true }
pallet-identity = { workspace = true }
pallet-preimage = { workspace = true }

# substrate primitives
sp-io = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sp-genesis-builder = { workspace = true }

# Frontier
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }
pallet-ethereum = { workspace = true, features = ["forbid-evm-reentrancy"] }
pallet-base-fee = { workspace = true }
fp-self-contained = { workspace = true, features = ["serde"] }
fp-evm = { workspace = true, features = ["serde"] }
fp-rpc = { workspace = true }
fp-rpc-debug = { workspace = true }
fp-rpc-txpool = { workspace = true }
fp-rpc-evm-tracing-events = { workspace = true, optional = true }
fp-account = { workspace = true, features = ["serde"] }
evm-tracer = { workspace = true, optional = true }

# Custom Pallets
pallet-bfc-staking = { workspace = true }
pallet-bfc-utility = { workspace = true }
pallet-bfc-offences = { workspace = true }
pallet-relay-manager = { workspace = true }

# Precompiled Contracts
pallet-evm-precompile-simple = { workspace = true }
pallet-evm-precompile-bn128 = { workspace = true }
pallet-evm-precompile-modexp = { workspace = true }
pallet-evm-precompile-blake2 = { workspace = true }

precompile-bfc-staking = { workspace = true }
precompile-bfc-offences = { workspace = true }
precompile-relay-manager = { workspace = true }
precompile-governance = { workspace = true }
precompile-collective = { workspace = true }
precompile-balance = { workspace = true }

[build-dependencies]
substrate-wasm-builder = { workspace = true }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"bifrost-common-runtime/std",
	"bp-core/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-treasury/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-authorship/std",
	"pallet-utility/std",
	"pallet-collective/std",
	"pallet-democracy/std",
	"pallet-membership/std",
	"pallet-evm/std",
	"pallet-ethereum/std",
	"pallet-base-fee/std",
	"pallet-bfc-staking/std",
	"pallet-bfc-utility/std",
	"pallet-bfc-offences/std",
	"pallet-relay-manager/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-identity/std",
	"pallet-preimage/std",
	"sp-api/std",
	"sp-consensus-aura/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-io/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"fp-self-contained/std",
	"fp-evm/std",
	"fp-rpc/std",
	"fp-rpc-debug/std",
	"fp-rpc-txpool/std",
	"fp-rpc-evm-tracing-events/std",
	"fp-account/std",
	"evm-tracer/std",
	"precompile-utils/std",
]
evm-tracing = [
	"rlp",
	"sha3",
	"evm-tracer",
	"sp-io/disable_oom",
	"sp-io/disable_panic_handler",
	"fp-rpc-evm-tracing-events",
]
runtime-wasm = []
runtime-benchmarks = [
	"hex-literal",
	"sp-runtime/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
]
