// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_tranche_system`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /Users/alexwon/workspace/pilab/bifrost/polkadot-sdk-patched/target/release/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/target/release/wbuild/bifrost-dev-runtime/bifrost_dev_runtime.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --allow-missing-host-functions
// --pallet
// pallet_tranche_system
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --output
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/pallets/omnifi/tranche-system/src/weights.rs
// --template
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_tranche_system`.
pub trait WeightInfo {
	fn create_product(t: u32, a: u32) -> Weight;
	fn create_single_chain_product(t: u32, a: u32) -> Weight;
	fn set_tranche(t: u32, a: u32) -> Weight;
	fn set_adapters(t: u32, a: u32, n: u32) -> Weight;
	fn set_multichain_adapters(t: u32, o: u32, n: u32) -> Weight;
	fn set_orchestrator_address() -> Weight;
	fn set_multichain_tranche_managers(t: u32, a: u32) -> Weight;
	fn set_request_flow_version() -> Weight;
	fn set_settlement_flow_version() -> Weight;
	fn create_product_permissionless(t: u32, a: u32) -> Weight;
	fn create_single_chain_product_permissionless(t: u32, a: u32) -> Weight;
}

/// Weights for `pallet_tranche_system` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:100 w:100)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:99 w:99)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `a` is `[2, 110]`.
	fn create_product(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3716 + a * (2317 ±0) + t * (2540 ±0)`
		// Minimum execution time: 396_000_000 picoseconds.
		Weight::from_parts(31_271_690, 3716)
			// Standard Error: 39_073
			.saturating_add(Weight::from_parts(3_602_937, 0).saturating_mul(t.into()))
			// Standard Error: 35_736
			.saturating_add(Weight::from_parts(6_102_851, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2317).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2540).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:10 w:10)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 10]`.
	/// The range of component `a` is `[1, 10]`.
	fn create_single_chain_product(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3716 + a * (2539 ±0) + t * (2540 ±0)`
		// Minimum execution time: 55_000_000 picoseconds.
		Weight::from_parts(15_189_678, 3716)
			// Standard Error: 6_718
			.saturating_add(Weight::from_parts(3_468_214, 0).saturating_mul(t.into()))
			// Standard Error: 6_718
			.saturating_add(Weight::from_parts(5_940_083, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2539).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2540).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:1)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 99]`.
	/// The range of component `a` is `[2, 110]`.
	fn set_tranche(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1156 + a * (720 ±0) + t * (138 ±0)`
		//  Estimated: `4290 + a * (724 ±0) + t * (136 ±0)`
		// Minimum execution time: 73_000_000 picoseconds.
		Weight::from_parts(15_976_773, 4290)
			// Standard Error: 2_379
			.saturating_add(Weight::from_parts(522_704, 0).saturating_mul(t.into()))
			// Standard Error: 2_149
			.saturating_add(Weight::from_parts(2_869_591, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 724).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 136).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:11)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `a` is `[2, 99]`.
	/// The range of component `n` is `[1, 10]`.
	fn set_adapters(t: u32, a: u32, n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251 + a * (738 ±0) + n * (137 ±0) + t * (134 ±0)`
		//  Estimated: `3794 + a * (741 ±0) + n * (2539 ±1) + t * (134 ±0)`
		// Minimum execution time: 131_000_000 picoseconds.
		Weight::from_parts(7_856_726, 3794)
			// Standard Error: 2_253
			.saturating_add(Weight::from_parts(516_045, 0).saturating_mul(t.into()))
			// Standard Error: 2_283
			.saturating_add(Weight::from_parts(2_942_569, 0).saturating_mul(a.into()))
			// Standard Error: 23_316
			.saturating_add(Weight::from_parts(6_892_406, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 741).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2539).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 134).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:20)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:99 w:199)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `o` is `[2, 110]`.
	/// The range of component `n` is `[2, 110]`.
	fn set_multichain_adapters(t: u32, o: u32, n: u32, ) -> Weight {
		// Generated with `--output-analysis median-slopes`: min-squares extrapolated a
		// spurious 322M ps intercept from the max-held sweeps.
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (23 ±0) + o * (761 ±0) + t * (134 ±0)`
		//  Estimated: `1715 + n * (2308 ±0) + o * (761 ±0) + t * (134 ±0)`
		// Minimum execution time: 322_000_000 picoseconds.
		Weight::from_parts(0, 1715)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(500_000, 0).saturating_mul(t.into()))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(2_710_843, 0).saturating_mul(o.into()))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(6_715_909, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(o.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2308).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 761).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 134).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::OrchestratorAddress` (r:0 w:1)
	/// Proof: `TrancheSystem::OrchestratorAddress` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_orchestrator_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `a` is `[2, 110]`.
	fn set_multichain_tranche_managers(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `757 + a * (720 ±0) + t * (134 ±0)`
		//  Estimated: `4013 + a * (723 ±0) + t * (132 ±0)`
		// Minimum execution time: 67_000_000 picoseconds.
		Weight::from_parts(11_351_897, 4013)
			// Standard Error: 3_964
			.saturating_add(Weight::from_parts(514_035, 0).saturating_mul(t.into()))
			// Standard Error: 3_626
			.saturating_add(Weight::from_parts(2_850_782, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 723).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 132).saturating_mul(t.into()))
	}
	fn set_request_flow_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
	}
	fn set_settlement_flow_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
	}
	/// Storage: `TranchePermissions::ProductAdmins` (r:1 w:1)
	/// Proof: `TranchePermissions::ProductAdmins` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:100 w:100)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:99 w:99)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `a` is `[2, 110]`.
	fn create_product_permissionless(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3757 + a * (2317 ±0) + t * (2540 ±0)`
		// Minimum execution time: 402_000_000 picoseconds.
		Weight::from_parts(20_371_053, 3757)
			// Standard Error: 9_513
			.saturating_add(Weight::from_parts(3_708_289, 0).saturating_mul(t.into()))
			// Standard Error: 8_701
			.saturating_add(Weight::from_parts(6_201_524, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2317).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2540).saturating_mul(t.into()))
	}
	/// Storage: `TranchePermissions::ProductAdmins` (r:1 w:1)
	/// Proof: `TranchePermissions::ProductAdmins` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:10 w:10)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 10]`.
	/// The range of component `a` is `[1, 10]`.
	fn create_single_chain_product_permissionless(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3757 + a * (2539 ±0) + t * (2540 ±0)`
		// Minimum execution time: 59_000_000 picoseconds.
		Weight::from_parts(19_819_184, 3757)
			// Standard Error: 7_719
			.saturating_add(Weight::from_parts(3_478_904, 0).saturating_mul(t.into()))
			// Standard Error: 7_719
			.saturating_add(Weight::from_parts(5_988_847, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2539).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2540).saturating_mul(t.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:100 w:100)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:99 w:99)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `a` is `[2, 110]`.
	fn create_product(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3716 + a * (2317 ±0) + t * (2540 ±0)`
		// Minimum execution time: 396_000_000 picoseconds.
		Weight::from_parts(31_271_690, 3716)
			// Standard Error: 39_073
			.saturating_add(Weight::from_parts(3_602_937, 0).saturating_mul(t.into()))
			// Standard Error: 35_736
			.saturating_add(Weight::from_parts(6_102_851, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2317).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2540).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:10 w:10)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 10]`.
	/// The range of component `a` is `[1, 10]`.
	fn create_single_chain_product(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3716 + a * (2539 ±0) + t * (2540 ±0)`
		// Minimum execution time: 55_000_000 picoseconds.
		Weight::from_parts(15_189_678, 3716)
			// Standard Error: 6_718
			.saturating_add(Weight::from_parts(3_468_214, 0).saturating_mul(t.into()))
			// Standard Error: 6_718
			.saturating_add(Weight::from_parts(5_940_083, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2539).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2540).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:1)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 99]`.
	/// The range of component `a` is `[2, 110]`.
	fn set_tranche(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1156 + a * (720 ±0) + t * (138 ±0)`
		//  Estimated: `4290 + a * (724 ±0) + t * (136 ±0)`
		// Minimum execution time: 73_000_000 picoseconds.
		Weight::from_parts(15_976_773, 4290)
			// Standard Error: 2_379
			.saturating_add(Weight::from_parts(522_704, 0).saturating_mul(t.into()))
			// Standard Error: 2_149
			.saturating_add(Weight::from_parts(2_869_591, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 724).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 136).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:11)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `a` is `[2, 99]`.
	/// The range of component `n` is `[1, 10]`.
	fn set_adapters(t: u32, a: u32, n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251 + a * (738 ±0) + n * (137 ±0) + t * (134 ±0)`
		//  Estimated: `3794 + a * (741 ±0) + n * (2539 ±1) + t * (134 ±0)`
		// Minimum execution time: 131_000_000 picoseconds.
		Weight::from_parts(7_856_726, 3794)
			// Standard Error: 2_253
			.saturating_add(Weight::from_parts(516_045, 0).saturating_mul(t.into()))
			// Standard Error: 2_283
			.saturating_add(Weight::from_parts(2_942_569, 0).saturating_mul(a.into()))
			// Standard Error: 23_316
			.saturating_add(Weight::from_parts(6_892_406, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 741).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2539).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 134).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:20)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:99 w:199)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `o` is `[2, 110]`.
	/// The range of component `n` is `[2, 110]`.
	fn set_multichain_adapters(t: u32, o: u32, n: u32, ) -> Weight {
		// Generated with `--output-analysis median-slopes`: min-squares extrapolated a
		// spurious 322M ps intercept from the max-held sweeps.
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (23 ±0) + o * (761 ±0) + t * (134 ±0)`
		//  Estimated: `1715 + n * (2308 ±0) + o * (761 ±0) + t * (134 ±0)`
		// Minimum execution time: 322_000_000 picoseconds.
		Weight::from_parts(0, 1715)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(500_000, 0).saturating_mul(t.into()))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(2_710_843, 0).saturating_mul(o.into()))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(6_715_909, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(o.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2308).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 761).saturating_mul(o.into()))
			.saturating_add(Weight::from_parts(0, 134).saturating_mul(t.into()))
	}
	/// Storage: `TrancheSystem::OrchestratorAddress` (r:0 w:1)
	/// Proof: `TrancheSystem::OrchestratorAddress` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_orchestrator_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `a` is `[2, 110]`.
	fn set_multichain_tranche_managers(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `757 + a * (720 ±0) + t * (134 ±0)`
		//  Estimated: `4013 + a * (723 ±0) + t * (132 ±0)`
		// Minimum execution time: 67_000_000 picoseconds.
		Weight::from_parts(11_351_897, 4013)
			// Standard Error: 3_964
			.saturating_add(Weight::from_parts(514_035, 0).saturating_mul(t.into()))
			// Standard Error: 3_626
			.saturating_add(Weight::from_parts(2_850_782, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 723).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 132).saturating_mul(t.into()))
	}
	fn set_request_flow_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
	}
	fn set_settlement_flow_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
	}
	/// Storage: `TranchePermissions::ProductAdmins` (r:1 w:1)
	/// Proof: `TranchePermissions::ProductAdmins` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:100 w:100)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:99 w:99)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 100]`.
	/// The range of component `a` is `[2, 110]`.
	fn create_product_permissionless(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3757 + a * (2317 ±0) + t * (2540 ±0)`
		// Minimum execution time: 402_000_000 picoseconds.
		Weight::from_parts(20_371_053, 3757)
			// Standard Error: 9_513
			.saturating_add(Weight::from_parts(3_708_289, 0).saturating_mul(t.into()))
			// Standard Error: 8_701
			.saturating_add(Weight::from_parts(6_201_524, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2317).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2540).saturating_mul(t.into()))
	}
	/// Storage: `TranchePermissions::ProductAdmins` (r:1 w:1)
	/// Proof: `TranchePermissions::ProductAdmins` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:10 w:10)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 10]`.
	/// The range of component `a` is `[1, 10]`.
	fn create_single_chain_product_permissionless(t: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3757 + a * (2539 ±0) + t * (2540 ±0)`
		// Minimum execution time: 59_000_000 picoseconds.
		Weight::from_parts(19_819_184, 3757)
			// Standard Error: 7_719
			.saturating_add(Weight::from_parts(3_478_904, 0).saturating_mul(t.into()))
			// Standard Error: 7_719
			.saturating_add(Weight::from_parts(5_988_847, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2539).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2540).saturating_mul(t.into()))
	}
}
