// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_tranche_system`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /Users/alexwon/workspace/pilab/bifrost/polkadot-sdk-patched/target/release/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/target/release/wbuild/bifrost-dev-runtime/bifrost_dev_runtime.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --allow-missing-host-functions
// --pallet
// pallet_tranche_system
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --output
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/pallets/omnifi/tranche-system/src/weights.rs
// --template
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_tranche_system`.
pub trait WeightInfo {
	fn create_product() -> Weight;
	fn create_single_chain_product() -> Weight;
	fn set_tranche() -> Weight;
	fn set_adapters() -> Weight;
	fn set_multichain_adapters() -> Weight;
	fn set_orchestrator_address() -> Weight;
	fn set_multichain_tranche_managers() -> Weight;
	fn set_request_flow_version() -> Weight;
	fn set_settlement_flow_version() -> Weight;
}

/// Weights for `pallet_tranche_system` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:100 w:100)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:100 w:100)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn create_product() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `253790`
		// Minimum execution time: 1_244_000_000 picoseconds.
		Weight::from_parts(1_278_000_000, 253790)
			.saturating_add(T::DbWeight::get().reads(212_u64))
			.saturating_add(T::DbWeight::get().writes(213_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:10 w:10)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn create_single_chain_product() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `26270`
		// Minimum execution time: 89_000_000 picoseconds.
		Weight::from_parts(100_000_000, 26270)
			.saturating_add(T::DbWeight::get().reads(22_u64))
			.saturating_add(T::DbWeight::get().writes(23_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:1)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	fn set_tranche() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75717`
		//  Estimated: `79182`
		// Minimum execution time: 403_000_000 picoseconds.
		Weight::from_parts(438_000_000, 79182)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:20)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn set_adapters() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77276`
		//  Estimated: `80741`
		// Minimum execution time: 456_000_000 picoseconds.
		Weight::from_parts(472_000_000, 80741)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(21_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:20)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:100 w:200)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn set_multichain_adapters() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79374`
		//  Estimated: `253690`
		// Minimum execution time: 878_000_000 picoseconds.
		Weight::from_parts(907_000_000, 253690)
			.saturating_add(T::DbWeight::get().reads(111_u64))
			.saturating_add(T::DbWeight::get().writes(221_u64))
	}
	/// Storage: `TrancheSystem::OrchestratorAddress` (r:0 w:1)
	/// Proof: `TrancheSystem::OrchestratorAddress` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_orchestrator_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_multichain_tranche_managers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75224`
		//  Estimated: `78689`
		// Minimum execution time: 410_000_000 picoseconds.
		Weight::from_parts(433_000_000, 78689)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn set_request_flow_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
	}
	fn set_settlement_flow_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:100 w:100)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:100 w:100)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn create_product() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `253790`
		// Minimum execution time: 1_244_000_000 picoseconds.
		Weight::from_parts(1_278_000_000, 253790)
			.saturating_add(RocksDbWeight::get().reads(212_u64))
			.saturating_add(RocksDbWeight::get().writes(213_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:10 w:10)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:10)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::RequestFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::RequestFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::SettlementFlowVersion` (r:0 w:1)
	/// Proof: `TrancheSystem::SettlementFlowVersion` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn create_single_chain_product() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `26270`
		// Minimum execution time: 89_000_000 picoseconds.
		Weight::from_parts(100_000_000, 26270)
			.saturating_add(RocksDbWeight::get().reads(22_u64))
			.saturating_add(RocksDbWeight::get().writes(23_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:1)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	fn set_tranche() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75717`
		//  Estimated: `79182`
		// Minimum execution time: 403_000_000 picoseconds.
		Weight::from_parts(438_000_000, 79182)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:10 w:20)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn set_adapters() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77276`
		//  Estimated: `80741`
		// Minimum execution time: 456_000_000 picoseconds.
		Weight::from_parts(472_000_000, 80741)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(21_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:20)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:100 w:200)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn set_multichain_adapters() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79374`
		//  Estimated: `253690`
		// Minimum execution time: 878_000_000 picoseconds.
		Weight::from_parts(907_000_000, 253690)
			.saturating_add(RocksDbWeight::get().reads(111_u64))
			.saturating_add(RocksDbWeight::get().writes(221_u64))
	}
	/// Storage: `TrancheSystem::OrchestratorAddress` (r:0 w:1)
	/// Proof: `TrancheSystem::OrchestratorAddress` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_orchestrator_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:1)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_multichain_tranche_managers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75224`
		//  Estimated: `78689`
		// Minimum execution time: 410_000_000 picoseconds.
		Weight::from_parts(433_000_000, 78689)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn set_request_flow_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
	}
	fn set_settlement_flow_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
	}
}
