use crate::{EarningsEntry, PoolId};
use pallet_pools::{PermissionInspect, PoolInspect, PoolNAV};
use sp_core::U256;
use sp_runtime::DispatchError;

use frame_support::{pallet_prelude::*, traits::StorageVersion};
use frame_system::pallet_prelude::*;

#[frame_support::pallet]
pub mod pallet {
	use super::*;

	const STORAGE_VERSION: StorageVersion = StorageVersion::new(1);

	#[pallet::pallet]
	#[pallet::storage_version(STORAGE_VERSION)]
	pub struct Pallet<T>(_);

	#[pallet::config]
	pub trait Config: frame_system::Config<RuntimeEvent: From<Event<Self>>> {
		/// Pool inspection — implemented by pallet-pools.
		/// Used to verify that the target pool exists before accepting an earnings submission.
		type Pools: PoolInspect;
		/// Permission inspection — implemented by pallet-permissions.
		/// Used to verify that the caller holds the `OracleFeeder` role for the pool.
		type Permissions: PermissionInspect<Self::AccountId>;
	}

	// -----------------------------------------------------------------------
	// Errors
	// -----------------------------------------------------------------------

	#[pallet::error]
	pub enum Error<T> {
		/// No pool exists with this ID.
		PoolNotFound,
		/// Caller does not hold the OracleFeeder role for this pool.
		Unauthorized,
	}

	// -----------------------------------------------------------------------
	// Events
	// -----------------------------------------------------------------------

	#[pallet::event]
	#[pallet::generate_deposit(pub(crate) fn deposit_event)]
	pub enum Event<T: Config> {
		/// An oracle feeder submitted a cumulative earnings snapshot for a pool.
		EarningsSubmitted { pool_id: PoolId, feeder: T::AccountId, cumulative_earnings: U256 },
	}

	// -----------------------------------------------------------------------
	// Storage
	// -----------------------------------------------------------------------

	/// Stores the latest cumulative earnings snapshot per pool, as submitted by the oracle feeder.
	#[pallet::storage]
	pub type PoolEarnings<T: Config> = StorageMap<_, Blake2_128Concat, PoolId, EarningsEntry>;

	// -----------------------------------------------------------------------
	// Extrinsics
	// -----------------------------------------------------------------------

	#[pallet::call]
	impl<T: Config> Pallet<T> {
		/// Submit a cumulative earnings snapshot for a pool.
		///
		/// The caller must hold the `OracleFeeder` role for `pool_id`
		/// (granted by the pool admin via `pallet-permissions`).
		///
		/// `cumulative_earnings` is the total off-chain earnings generated by the institution
		/// since pool inception. It should be monotonically increasing across submissions;
		/// decreasing values are accepted only for self-correction of erroneous prior submissions.
		///
		/// `pallet-pools` computes the final oracle NAV as:
		///   `oracle_nav = total_borrowed + (cumulative_earnings − repaid_earnings)`
		#[pallet::call_index(0)]
		#[pallet::weight(Weight::from_parts(5_000, 0))]
		pub fn submit_earnings(
			origin: OriginFor<T>,
			pool_id: PoolId,
			cumulative_earnings: U256,
		) -> DispatchResult {
			let who = ensure_signed(origin)?;
			ensure!(T::Pools::pool_exists(pool_id), Error::<T>::PoolNotFound);
			ensure!(T::Permissions::is_oracle_feeder(pool_id, &who), Error::<T>::Unauthorized);

			let block: u32 = frame_system::Pallet::<T>::block_number().try_into().unwrap_or(0);

			PoolEarnings::<T>::insert(
				pool_id,
				EarningsEntry { cumulative_earnings, updated_block: block },
			);

			Self::deposit_event(Event::EarningsSubmitted {
				pool_id,
				feeder: who,
				cumulative_earnings,
			});

			Ok(())
		}
	}

	// -----------------------------------------------------------------------
	// PoolNAV implementation
	// -----------------------------------------------------------------------

	impl<T: Config> PoolNAV<PoolId, U256> for Pallet<T> {
		/// Returns the latest `(cumulative_earnings, updated_block)` for the pool.
		///
		/// Returns `None` if no feeder has submitted data yet (e.g. immediately after pool
		/// creation). pallet-pools treats `None` as `cumulative_earnings = 0`, so
		/// `oracle_nav` falls back to `total_borrowed` alone until the first submission.
		fn nav(pool_id: PoolId) -> Option<(U256, u32)> {
			PoolEarnings::<T>::get(pool_id).map(|e| (e.cumulative_earnings, e.updated_block))
		}

		/// Returns the current `cumulative_earnings`, triggering no recomputation.
		///
		/// Returns `Ok(U256::zero())` if no feeder has submitted yet — matching the
		/// same `unwrap_or_default()` semantics that pallet-pools applies to `nav()`.
		fn update_nav(pool_id: PoolId) -> Result<U256, DispatchError> {
			Ok(Self::nav(pool_id).map(|(v, _)| v).unwrap_or_default())
		}
	}
}
