// SPDX-License-Identifier: GPL-3.0-only
pragma solidity >=0.8.0;

/**
 * @title Investments Precompile Interface (tranche-system draft)
 * @notice Called exclusively by the product's registered Valuation contract
 *         (the `valuation.address` set in pallet-tranche-system's `create_product`) —
 *         there is no Gateway in this call path. This pallet is a pure ledger —
 *         all pricing and allocation decisions are made by the Valuation Contract;
 *         this interface only records those decisions into pallet-tranche-investments.
 *
 * Address: 0x0000000000000000000000000000000000000201
 */
interface Investments {
    /// @dev One slice of a request's approval: `amount` was allocated to the
    ///      MultichainAdapter identified by (`adapter_address`, `adapter_chain_id`).
    struct Allocation {
        address adapter_address;
        uint64 adapter_chain_id;
        uint256 amount;
    }

    /// @dev Adapter-level NAV breakdown for one settlement — one entry per Adapter within a
    ///      product. Field naming/shape intentionally mirrors the node's own base valuation
    ///      record format (chainId, adapter, epochId, valuationCutoff), not this file's usual
    ///      snake_case convention, so the pallet-side type and any off-chain indexer consuming
    ///      both share field semantics 1:1.
    /// @param chainId         EVM chain ID the adapter lives on — combined with `adapter`, this
    ///                        is the adapter's global identity (chainId, adapter)
    /// @param adapter         Adapter contract address on that chain
    /// @param epochId         Adapter's own local epoch/settlement counter
    /// @param valuationCutoff Timestamp this valuation was struck as-of
    /// @param principal       Cumulative principal deployed into this adapter
    /// @param positions       Per-asset breakdown of this adapter's current holdings
    struct AdapterValuation {
        uint64 chainId;
        address adapter;
        uint256 epochId;
        uint64 valuationCutoff;
        uint256 principal;
        AssetPosition[] positions;
    }

    /// @param asset    Asset's token address on `chainId` (native to that chain, not a Hub address)
    /// @param amount   Held amount, in `asset`'s own decimals
    /// @param priceUsd Price at valuation time, FixedU128-style 1e18 fixed-point (sourced from
    ///                 the Adapter's own NAV oracle, not this pallet)
    /// @param usdValue `amount * priceUsd`, recorded alongside `amount`/`priceUsd` rather than
    ///                 only stored, so downstream consumers can re-derive and cross-check it
    ///                 without re-fetching price data
    /// @param counted  Whether this position counts toward the adapter's NAV — pre-swap reward
    ///                 tokens are `false` (see design doc §4)
    struct AssetPosition {
        address asset;
        uint256 amount;
        uint256 priceUsd;
        uint256 usdValue;
        bool counted;
    }

    event InvestmentRequested(
        uint256 product_id,
        uint64 vault_chain_id,
        address vault_address,
        address investor_address,
        uint256 amount,
        uint256 request_id,
        uint256 settlement_id,
        uint8 order_type
    );
    event InvestmentApproved(
        uint256 product_id,
        uint256 request_id,
        uint256 settlement_id,
        Allocation[] allocations,
        uint256 claimable_assets
    );
    event InvestmentCancelled(
        uint256 product_id,
        uint256 request_id,
        uint256 settlement_id
    );
    event AdapterValuationsRecorded(
        uint256 product_id,
        uint256 settlement_id,
        AdapterValuation[] valuations
    );
    event ProductNavRecorded(
        uint256 product_id,
        uint256 settlement_id,
        uint256 product_nav
    );

    /**
     * @notice Record a pending deposit or redeem request as it arrives at the
     *         Valuation Contract, before any Adapter allocation has happened.
     * @dev Only callable by the calling product's registered Valuation contract
     *      address — `msg.sender` must equal the `valuation.address` stored for
     *      `product_id` in pallet-tranche-system.
     *      Stores the full requested amount under `request_id` in
     *      RequestedInvestments. Emits InvestmentRequested on success.
     * @param product_id       The product this request belongs to
     * @param investor_address Investor address on the external chain
     * @param vault_chain_id   EVM chain ID of the chain where the tranche vault is deployed
     * @param vault_address    ERC-7540 vault contract address on that chain
     * @param amount           Investor's full requested deposit/redeem amount (18-decimal U256, pre-allocation)
     * @param request_id       Unique request identifier, generated by the Valuation Contract
     * @param settlement_id    Valuation Contract's settlement cycle in effect at request time
     * @param order_type       0 = redeem, 1 = deposit
     */
    function record_investment_request(
        uint256 product_id,
        address investor_address,
        uint64 vault_chain_id,
        address vault_address,
        uint256 amount,
        uint256 request_id,
        uint256 settlement_id,
        uint8 order_type
    ) external;

    /**
     * @notice Record a pending request's full approval: the complete breakdown
     *         of how it was allocated across Adapters, plus what the investor
     *         can claim as a result.
     * @dev Only callable by the calling product's registered Valuation contract
     *      address. Called exactly once per request_id — `allocations` carries
     *      the full allocation breakdown in one call, so the pallet can mint/pay
     *      out immediately without needing to detect "last slice received."
     *      The sum of `allocations[i].amount` is expected to equal the original
     *      request's amount (any portion deliberately held back as reserve
     *      should still be accounted for by an explicit entry, not omitted).
     *      `order_type` is not a parameter here — it was already recorded
     *      against `request_id` by record_investment_request and is looked up
     *      from the pending entry rather than passed again; `claimable_assets`
     *      is interpreted using that stored order_type: the minted share-token
     *      amount for a deposit request, or the released underlying-asset
     *      amount for a redeem request.
     *      Moves the entry from RequestedInvestments to ApprovedInvestments.
     *      Emits InvestmentApproved on success.
     * @param product_id       The product this approval belongs to
     * @param request_id       The pending request being approved
     * @param settlement_id    Valuation Contract's settlement cycle this approval settles in
     * @param allocations      Per-Adapter allocation breakdown of the request's amount
     * @param claimable_assets Finalized claimable amount for the investor — shares (deposit) or assets (redeem), per the request's order_type
     */
    function record_investment_approval(
        uint256 product_id,
        uint256 request_id,
        uint256 settlement_id,
        Allocation[] calldata allocations,
        uint256 claimable_assets
    ) external;

    /**
     * @notice Record the cancellation of a pending request before it has been
     *         approved/allocated.
     * @dev Only callable by the calling product's registered Valuation contract
     *      address. `order_type` is not a parameter — it's already known from
     *      the pending entry stored under `request_id`.
     *      Removes the entry from RequestedInvestments.
     *      Emits InvestmentCancelled on success.
     * @param product_id     The product this cancellation belongs to
     * @param request_id     The pending request being cancelled
     * @param settlement_id  Valuation Contract's settlement cycle the pending request belongs to
     */
    function record_investment_cancellation(
        uint256 product_id,
        uint256 request_id,
        uint256 settlement_id
    ) external;

    /**
     * @notice Record the finalized per-Adapter NAV breakdown for a settlement, once the
     *         Valuation Contract has completed that settlement cycle.
     * @dev Only callable by the product's registered Valuation contract address.
     *      Renamed from `record_settlement_info` (2026-07-28), and `nav_infos` changed from
     *      `bytes[]` to `AdapterValuation[]` — the old opaque-bytes shape existed to let the
     *      payload vary by a leading `structure_type` discriminant byte without changing this
     *      function's signature; now that the shape is a fixed struct (one entry per Adapter),
     *      that flexibility is gone, so the name narrows to match what this call actually
     *      records. The settlement's aggregate total is a separate call — see
     *      `record_product_nav` below.
     *      Emits AdapterValuationsRecorded on success.
     * @param product_id     The product this settlement belongs to
     * @param settlement_id  Valuation Contract's settlement cycle this info belongs to
     * @param valuations     Per-Adapter NAV breakdown for this settlement, one entry per Adapter
     */
    function record_adapter_valuations(
        uint256 product_id,
        uint256 settlement_id,
        AdapterValuation[] calldata valuations
    ) external;

    /**
     * @notice Record the settlement's finalized aggregate NAV across all of the product's
     *         sources, once the Valuation Contract has completed that settlement cycle.
     * @dev Only callable by the product's registered Valuation contract address.
     *      `product_nav` is the finalized total across all of the product's sources (both
     *      OnchainSource adapters, read live by Valuation, and OffchainSource adapters, fed
     *      via pallet-rwa-nav-oracle) — the aggregate figure Valuation actually used for this
     *      settlement's waterfall/share-price computation. Not independently verified by this
     *      pallet against `record_adapter_valuations`'s breakdown — Valuation is trusted for
     *      the aggregation, same as it's trusted for every other value in this interface.
     *      Emits ProductNavRecorded on success.
     * @param product_id     The product this settlement belongs to
     * @param settlement_id  Valuation Contract's settlement cycle this NAV belongs to
     * @param product_nav    Finalized total NAV across all sources for this settlement (sum, not per-source)
     */
    function record_product_nav(
        uint256 product_id,
        uint256 settlement_id,
        uint256 product_nav
    ) external;
}
