// SPDX-License-Identifier: GPL-3.0-only
pragma solidity >=0.8.0;

/**
 * @title Investments Precompile Interface (tranche-system draft)
 * @notice Called exclusively by the product's registered Valuation contract
 *         (the `valuation.address` set in pallet-tranche-system's `create_product`) —
 *         there is no Gateway in this call path. This pallet is a pure ledger —
 *         all pricing and allocation decisions are made by the Valuation Contract;
 *         this interface only records those decisions into pallet-tranche-investments.
 *
 * Address: 0x0000000000000000000000000000000000000201
 */
interface Investments {
    /// @dev One slice of a request's approval: `amount` was allocated to the
    ///      MultichainAdapter identified by (`adapter_address`, `adapter_chain_id`).
    struct Allocation {
        address adapter_address;
        uint64 adapter_chain_id;
        uint256 amount;
    }

    event InvestmentRequested(
        uint256 product_id,
        uint64 vault_chain_id,
        address vault_address,
        address investor_address,
        uint256 amount,
        uint256 request_id,
        uint256 settlement_id,
        uint8 order_type
    );
    event InvestmentApproved(
        uint256 product_id,
        uint256 request_id,
        uint256 settlement_id,
        Allocation[] allocations,
        uint256 claimable_assets
    );
    event InvestmentCancelled(
        uint256 product_id,
        uint256 request_id,
        uint256 settlement_id
    );
    event SettlementInfoRecorded(
        uint256 product_id,
        uint256 settlement_id,
        bytes[] nav_infos
    );

    /**
     * @notice Record a pending deposit or redeem request as it arrives at the
     *         Valuation Contract, before any Adapter allocation has happened.
     * @dev Only callable by the calling product's registered Valuation contract
     *      address — `msg.sender` must equal the `valuation.address` stored for
     *      `product_id` in pallet-tranche-system.
     *      Stores the full requested amount under `request_id` in
     *      RequestedInvestments. Emits InvestmentRequested on success.
     * @param product_id       The product this request belongs to
     * @param investor_address Investor address on the external chain
     * @param vault_chain_id   EVM chain ID of the chain where the tranche vault is deployed
     * @param vault_address    ERC-7540 vault contract address on that chain
     * @param amount           Investor's full requested deposit/redeem amount (18-decimal U256, pre-allocation)
     * @param request_id       Unique request identifier, generated by the Valuation Contract
     * @param settlement_id    Valuation Contract's settlement cycle in effect at request time
     * @param order_type       0 = redeem, 1 = deposit
     */
    function record_investment_request(
        uint256 product_id,
        address investor_address,
        uint64 vault_chain_id,
        address vault_address,
        uint256 amount,
        uint256 request_id,
        uint256 settlement_id,
        uint8 order_type
    ) external;

    /**
     * @notice Record a pending request's full approval: the complete breakdown
     *         of how it was allocated across Adapters, plus what the investor
     *         can claim as a result.
     * @dev Only callable by the calling product's registered Valuation contract
     *      address. Called exactly once per request_id — `allocations` carries
     *      the full allocation breakdown in one call, so the pallet can mint/pay
     *      out immediately without needing to detect "last slice received."
     *      The sum of `allocations[i].amount` is expected to equal the original
     *      request's amount (any portion deliberately held back as reserve
     *      should still be accounted for by an explicit entry, not omitted).
     *      `order_type` is not a parameter here — it was already recorded
     *      against `request_id` by record_investment_request and is looked up
     *      from the pending entry rather than passed again; `claimable_assets`
     *      is interpreted using that stored order_type: the minted share-token
     *      amount for a deposit request, or the released underlying-asset
     *      amount for a redeem request.
     *      Moves the entry from RequestedInvestments to ApprovedInvestments.
     *      Emits InvestmentApproved on success.
     * @param product_id       The product this approval belongs to
     * @param request_id       The pending request being approved
     * @param settlement_id    Valuation Contract's settlement cycle this approval settles in
     * @param allocations      Per-Adapter allocation breakdown of the request's amount
     * @param claimable_assets Finalized claimable amount for the investor — shares (deposit) or assets (redeem), per the request's order_type
     */
    function record_investment_approval(
        uint256 product_id,
        uint256 request_id,
        uint256 settlement_id,
        Allocation[] calldata allocations,
        uint256 claimable_assets
    ) external;

    /**
     * @notice Record the cancellation of a pending request before it has been
     *         approved/allocated.
     * @dev Only callable by the calling product's registered Valuation contract
     *      address. `order_type` is not a parameter — it's already known from
     *      the pending entry stored under `request_id`.
     *      Removes the entry from RequestedInvestments.
     *      Emits InvestmentCancelled on success.
     * @param product_id     The product this cancellation belongs to
     * @param request_id     The pending request being cancelled
     * @param settlement_id  Valuation Contract's settlement cycle the pending request belongs to
     */
    function record_investment_cancellation(
        uint256 product_id,
        uint256 request_id,
        uint256 settlement_id
    ) external;

    /**
     * @notice Record the finalized per-source NAV breakdown for a settlement,
     *         once the Valuation Contract has completed that settlement cycle.
     * @dev Only callable by the product's registered Valuation contract address.
     *      Each entry of `nav_infos` is a raw packed encoding rather than a fixed
     *      struct, so that the payload shape can vary by `structure_type` without
     *      changing this function's signature. The layout as currently specified is:
     *        abi.encodePacked(uint8 structure_type, uint256 timestamp, address adapter, uint256 epoch_id)
     *      `structure_type` is the entry's leading discriminant byte; decoders must
     *      branch on it before parsing the remainder of the entry.
     *      Emits SettlementInfoRecorded on success.
     * @param product_id     The product this settlement belongs to
     * @param settlement_id  Valuation Contract's settlement cycle this info belongs to
     * @param nav_infos      Per-source NAV records for this settlement, one packed entry per source
     */
    function record_settlement_info(
        uint256 product_id,
        uint256 settlement_id,
        bytes[] calldata nav_infos
    ) external;
}
