[package]
name = "bp-multi-sig"
version = "0.0.1"
description = "Primitives for multi-signature accounts"
authors = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
miniscript = { workspace = true }

scale-info = { workspace = true }
parity-scale-codec = { workspace = true }

sp-std = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"scale-info/std",
	"parity-scale-codec/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
]
