#![cfg_attr(not(feature = "std"), no_std)]

mod pallet;
pub mod weights;

pub use pallet::pallet::*;
pub use weights::WeightInfo;

use pallet_tranche_system::{ProductId, VaultId};
use parity_scale_codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use sp_core::{H160, H256, U256};
use sp_runtime::RuntimeDebug;
use sp_std::marker::PhantomData;

// ---------------------------------------------------------------------------
// Primitive type aliases
// ---------------------------------------------------------------------------

/// Opaque request identifier, generated by the Valuation Contract — only unique
/// within a product's own namespace. Same underlying type as
/// `pallet_tranche_investments::RequestId`; declared locally rather than
/// imported so this pallet has no hard dependency on tranche-investments (see
/// interface.sol's DRAFT note on why the two precompiles were split apart).
pub type RequestId = H256;

/// Opaque settlement-cycle identifier, generated by the Valuation Contract —
/// only unique within a product's own namespace. Same underlying type as
/// `pallet_tranche_investments::SettlementId`, declared locally for the same
/// reason as `RequestId` above.
pub type SettlementId = U256;

/// EVM chain ID. Bare `u64`, matching `pallet_tranche_system::VaultId::chain_id`
/// — no dedicated newtype exists elsewhere in this pallet family.
pub type ChainId = u64;

/// Maximum number of spoke chains a single settlement can register in
/// `SettlementSpokeChains`. Reuses pallet-tranche-system's
/// `MAX_ADAPTERS_PER_MULTICHAIN_ADAPTER` rather than defining a fresh bound —
/// a settlement's spoke-chain fan-out is ultimately bounded by how many
/// chains a product's own MultichainAdapters span, same rationale as
/// `pallet_tranche_investments::MAX_ALLOCATIONS` reusing
/// `MAX_MULTICHAIN_ADAPTERS`.
pub const MAX_SPOKE_CHAINS: u32 = pallet_tranche_system::MAX_ADAPTERS_PER_MULTICHAIN_ADAPTER;

// ---------------------------------------------------------------------------
// TxRecord
// ---------------------------------------------------------------------------

/// Stored off-chain tx evidence, accepted from the tx recorder's attestation.
/// Mirrors interface.sol's `TxRecord`, except `recorded_at == 0` is not used as
/// an unset sentinel here — that was a Solidity-only workaround for the lack of
/// an `Option` type; on this side, "not yet recorded" is represented directly
/// as `Option<TxRecord<BlockNumber>>` at every storage/query site instead. The
/// precompile boundary (`precompiles/tranche-tx-registry`) is responsible for
/// translating `None` back into a zeroed struct with `recorded_at == 0` when it
/// encodes a response for a Solidity caller.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct TxRecord<BlockNumber> {
	/// EVM chain ID the tx occurred on.
	pub chain_id: ChainId,
	/// Transaction hash on that chain.
	pub tx_hash: H256,
	/// This chain's own block number when the attestation was accepted.
	pub recorded_at: BlockNumber,
}

// ---------------------------------------------------------------------------
// Request pipeline
// ---------------------------------------------------------------------------

/// Step within the 3-tx request pipeline, in order. Mirrors interface.sol's
/// `RequestStep`.
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum RequestStep {
	Requested,
	BridgeExecuted,
	HooksExecuted,
}

/// 0 = redeem, 1 = deposit — mirrors interface.sol's `order_type` and
/// `pallet_tranche_investments::OrderType` exactly (same shape, declared
/// locally for the same no-hard-dependency reason as `RequestId` above).
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum OrderType {
	Redeem,
	Deposit,
}

/// Data supplied only when opening a fresh `RequestEntries` entry
/// (`record_request_tx` with `step == RequestStep::Requested`). Bundled into
/// one `Option` at the extrinsic boundary rather than four separate
/// `Option`s, so "provided" and "not provided" can't disagree field-by-field
/// — see `RequestEntry`'s doc comment for why `settlement_id` isn't here.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct RequestOpening {
	pub investor: H160,
	pub vault: VaultId,
	pub amount: U256,
	pub order_type: OrderType,
}

/// A request's 3-tx registry entry. Keyed by `(product_id, request_id)` in
/// storage — `product_id` is still embedded here too (not just in the map key),
/// same convention as `pallet_tranche_investments::RequestedInvestment`, so a
/// value read out of storage carries enough context to act on independent of
/// the key it was fetched with.
///
/// `vault`/`investor`/`amount`/`order_type` are only known once the
/// `Requested` step is recorded — same as `investor` used to be the only such
/// field — and stay fixed from then on; only the three `TxRecord` fields
/// change on the two later steps. Mirrors most of
/// `pallet_tranche_investments::record_investment_request`'s parameter list
/// (its `product_id`/`request_id` are this entry's own storage keys instead
/// of fields) — `settlement_id` is deliberately NOT included: it isn't
/// actually knowable at request_tx time. It's assigned by the Valuation
/// Contract only once the request lands on the Hub and
/// `record_investment_request` runs; the Spoke-side bridge message itself
/// (Msg A / the redeem-request message) carries no settlement_id field for
/// the recorder to observe. So this entry gives investors/dashboards the
/// same request detail visibility during the `Requested`/`BridgeExecuted`
/// window that only exists officially in `pallet-tranche-investments` from
/// `HooksExecuted` onward — minus settlement_id, which isn't available any
/// earlier than that regardless.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct RequestEntry<BlockNumber> {
	pub product_id: ProductId,
	/// The tranche vault this request targets.
	pub vault: VaultId,
	/// Investor address the entry was opened with.
	pub investor: H160,
	/// Investor's full requested amount (pre-allocation), same units as
	/// `record_investment_request`'s `amount`.
	pub amount: U256,
	pub order_type: OrderType,
	/// Step 1: request_tx (Spoke).
	pub request_tx: Option<TxRecord<BlockNumber>>,
	/// Step 2: bridge_tx (Spoke -> Hub).
	pub bridge_tx: Option<TxRecord<BlockNumber>>,
	/// Step 3: hooks_tx (Hub).
	pub hooks_tx: Option<TxRecord<BlockNumber>>,
}

// ---------------------------------------------------------------------------
// Settlement pipeline
// ---------------------------------------------------------------------------

/// Step within the settlement pipeline. Mirrors interface.sol's
/// `SettlementStep`. `Queued`/`Triggered`/`Settled` are the three hub-level
/// states a future `get_settlement_status`-equivalent's hub-level status
/// moves through — `Queued` (not yet triggered), `Triggered` (triggered,
/// awaiting completion), `Settled` (every spoke chain has reached
/// `FinalizeHooksExecuted`). The other six describe one spoke chain's
/// own progress instead — a Collect/Response/Finalize leg crossed with a
/// Bridge/Hooks phase (each suffixed `Executed`, since by the time any of
/// these six is recorded, that half of the leg has already landed) —
/// flattened into this same enum so a single `step` parameter can select any
/// of them. `Queued` and `Settled` are read-only sentinels and must never be
/// accepted as `record_settlement_tx`'s extrinsic input (rejected with
/// `Error::InvalidSettlementStep`).
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum SettlementStep {
	Queued,
	Triggered,
	CollectBridgeExecuted,
	CollectHooksExecuted,
	ResponseBridgeExecuted,
	ResponseHooksExecuted,
	FinalizeBridgeExecuted,
	FinalizeHooksExecuted,
	Settled,
}

/// One spoke chain's full leg-by-leg registry entry within a
/// settlement. Keyed by `(product_id, settlement_id, spoke_chain_id)` in
/// storage — unlike interface.sol's `SettlementChainRecord`, `spoke_chain_id`
/// itself is NOT a field here, since it's already the storage map's own key
/// (no need to duplicate it into the value).
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
	Default,
)]
pub struct SettlementChainEntry<BlockNumber> {
	pub collect_bridge_tx: Option<TxRecord<BlockNumber>>,
	pub collect_hooks_tx: Option<TxRecord<BlockNumber>>,
	pub response_bridge_tx: Option<TxRecord<BlockNumber>>,
	pub response_hooks_tx: Option<TxRecord<BlockNumber>>,
	pub finalize_bridge_tx: Option<TxRecord<BlockNumber>>,
	pub finalize_hooks_tx: Option<TxRecord<BlockNumber>>,
}

// ---------------------------------------------------------------------------
// Receives
// ---------------------------------------------------------------------------

/// Which receivable pool a claim() tx drained (renamed from `ClaimKind`
/// 2026-08-06 — "Claim" as a term for this whole tracking pipeline was
/// replaced with "Receive" throughout; the underlying investor-facing
/// Solidity call being tracked is still literally named `claim()` on
/// TrancheVault, that's an external fact this rename doesn't change).
/// Mirrors interface.sol's `ReceiveKind` — TrancheManager pools receivable
/// amounts per (investor, vault), not per request_id, so redeem/deposit still
/// need distinguishing even though neither is tied to one specific request
/// anymore.
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum ReceiveKind {
	Redeem,
	Deposit,
}

/// One recorded claim() tx. Stored under `ReceiveEntries`' `(investor, vault,
/// tx_hash)` key — `product_id` is deliberately not part of the key at all
/// (unlike `RequestEntry`/settlement storage): `VaultId` is already globally
/// unique (enforced by pallet-tranche-system), so it would be redundant for
/// addressing purposes. `tx_hash` (inside `tx`, and also the key's third
/// level) is the claim's own natural unique identifier, so there's no
/// bounded-size cap or eviction logic needed the way a `Vec`-valued map would
/// require — one claim, one storage slot.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct ReceiveEntry<BlockNumber> {
	pub tx: TxRecord<BlockNumber>,
	pub kind: ReceiveKind,
}

// ---------------------------------------------------------------------------
// Tx recorder origin
// ---------------------------------------------------------------------------

/// `EnsureOrigin` that accepts only a signed origin matching the account
/// currently stored in `TxRecorder`. Unlike
/// `pallet_tranche_investments::EnsureValuation` (which checks a
/// precompile-constructed custom `Origin` variant), this checks an ordinary
/// signed extrinsic directly against pallet storage — same pattern as
/// `pallet_tranche_permissions::grant_permission`'s `ProductAdmins` check, just
/// promoted to a reusable `EnsureOrigin` impl since every `record_*` extrinsic
/// needs the identical check.
/// Wire as `type RecorderOrigin = pallet_tranche_tx_registry::EnsureTxRecorder<Runtime>`
/// in the runtime — see `Config::RecorderOrigin`.
pub struct EnsureTxRecorder<T>(PhantomData<T>);

impl<OuterOrigin, T> frame_support::traits::EnsureOrigin<OuterOrigin> for EnsureTxRecorder<T>
where
	T: pallet::pallet::Config,
	OuterOrigin: Into<Result<frame_system::RawOrigin<T::AccountId>, OuterOrigin>>
		+ From<frame_system::RawOrigin<T::AccountId>>,
{
	type Success = T::AccountId;

	fn try_origin(o: OuterOrigin) -> Result<Self::Success, OuterOrigin> {
		o.into().and_then(|raw| match raw {
			frame_system::RawOrigin::Signed(who)
				if pallet::pallet::TxRecorder::<T>::get().as_ref() == Some(&who) =>
			{
				Ok(who)
			},
			raw => Err(OuterOrigin::from(raw)),
		})
	}

	#[cfg(feature = "runtime-benchmarks")]
	fn try_successful_origin() -> Result<OuterOrigin, ()> {
		let recorder = pallet::pallet::TxRecorder::<T>::get().ok_or(())?;
		Ok(OuterOrigin::from(frame_system::RawOrigin::Signed(recorder)))
	}
}
