#![cfg_attr(not(feature = "std"), no_std)]

mod pallet;
pub mod weights;

pub use pallet::pallet::*;
pub use weights::WeightInfo;

use pallet_tranche_system::{ProductId, VaultId};
use parity_scale_codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use sp_core::{H160, H256, U256};
use sp_runtime::RuntimeDebug;
use sp_std::marker::PhantomData;

// ---------------------------------------------------------------------------
// Primitive type aliases
// ---------------------------------------------------------------------------

/// Opaque request identifier, generated by TrancheManager at request time (see
/// `pallet_tranche_investments::RequestId`'s doc comment for why it's known
/// this early, before the request ever reaches the Hub) — only unique within a
/// product's own namespace. Same underlying type as
/// `pallet_tranche_investments::RequestId`; declared locally rather than
/// imported so this pallet has no hard dependency on tranche-investments (see
/// interface.sol's DRAFT note on why the two precompiles were split apart).
pub type RequestId = H256;

/// Opaque settlement-cycle identifier, generated by the Valuation Contract —
/// only unique within a product's own namespace. Same underlying type as
/// `pallet_tranche_investments::SettlementId`, declared locally for the same
/// reason as `RequestId` above.
pub type SettlementId = U256;

/// EVM chain ID. Bare `u64`, matching `pallet_tranche_system::VaultId::chain_id`
/// — no dedicated newtype exists elsewhere in this pallet family.
pub type ChainId = u64;

/// Maximum number of spoke chains a single settlement can register in
/// `SettlementCollectResponseChains`/`SettlementFinalizeChains`, or a single
/// request can register in `RequestAdapterChains`. Reuses
/// pallet-tranche-system's
/// `MAX_ADAPTERS_PER_MULTICHAIN_ADAPTER` rather than defining a fresh bound —
/// either one's chain fan-out is ultimately bounded by how many chains a
/// product's own MultichainAdapters (plus, for a request, its own one vault)
/// span, same rationale as `pallet_tranche_investments::MAX_ALLOCATIONS`
/// reusing `MAX_MULTICHAIN_ADAPTERS`.
pub const MAX_SPOKE_CHAINS: u32 = pallet_tranche_system::MAX_ADAPTERS_PER_MULTICHAIN_ADAPTER;

// ---------------------------------------------------------------------------
// TxRecord
// ---------------------------------------------------------------------------

/// Stored off-chain tx evidence, accepted from the tx recorder's attestation.
/// Mirrors interface.sol's `TxRecord`, except `recorded_at == 0` is not used as
/// an unset sentinel here — that was a Solidity-only workaround for the lack of
/// an `Option` type; on this side, "not yet recorded" is represented directly
/// as `Option<TxRecord<BlockNumber>>` at every storage/query site instead. The
/// precompile boundary (`precompiles/tranche-tx-registry`) is responsible for
/// translating `None` back into a zeroed struct with `recorded_at == 0` when it
/// encodes a response for a Solidity caller.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct TxRecord<BlockNumber> {
	/// EVM chain ID the tx occurred on.
	pub chain_id: ChainId,
	/// Transaction hash on that chain.
	pub tx_hash: H256,
	/// This chain's own block number when the attestation was accepted.
	pub recorded_at: BlockNumber,
}

// ---------------------------------------------------------------------------
// Request pipeline
// ---------------------------------------------------------------------------

/// Step within a request's pipeline. Mirrors interface.sol's `RequestStep`.
/// `Requested`/`RequestBridgeExecuted`/`RequestQueued`/
/// `AdapterBridgeExecuted`/`AdapterApplied` are the only five
/// values `record_request_tx` ever accepts as input. Named after the
/// underlying Valuation Contract events wherever one exists 1:1 — `Requested`
/// (`DepositRequested`/`RedeemRequested`, at TrancheManager), `RequestQueued`
/// (`DepositQueued`/`RedeemQueued`, at Valuation), `AdapterApplied`
/// (`Supplied`/`WithdrawRequested`, at the MultichainAdapter) — so a recorder
/// can map "which event did I just see" to "which step do I record" without
/// needing to special-case Hub-vault vs Spoke-vault:
///
/// - `Requested` — the investor's request lands at TrancheManager, wherever
///   the vault is (Hub or Spoke). Opens the `RequestEntries` entry
///   (`investor`/`vault`/`amount`/`order_type`), never carries
///   `adapter_chain_ids` (not knowable yet — even for a Hub-vault request,
///   TrancheManager's event alone doesn't reveal the Adapter decision;
///   that's Valuation's job, one step later).
/// - (only if the vault is on a Spoke chain) `RequestBridgeExecuted` — the
///   *Inbound* leg's Bridge phase, Spoke -> Hub. At most one per request
///   (there's only one vault), so its evidence lives directly on
///   `RequestEntry` rather than per-chain. Never recorded for a Hub-vault
///   request — there's nothing to bridge when the vault is already on Hub.
/// - `RequestQueued` — the moment the request's capital is confirmed at the
///   Hub Valuation Contract and `adapter_chain_ids` becomes known, for
///   **both** Hub-vault and Spoke-vault requests alike. For a Hub-vault
///   request this typically lands in the very same transaction as
///   `Requested` (TrancheManager -> Valuation is a synchronous local call)
///   but is still a separate `record_request_tx` call — for a Spoke-vault
///   request it's the Inbound leg's own Hooks phase, only reachable once
///   `RequestBridgeExecuted` has landed. Evidence recorded on
///   `RequestEntry::queued_tx`.
/// - `AdapterBridgeExecuted`/`AdapterApplied`, once per declared
///   chain — the *Adapter* leg(s), the Hub Valuation Contract pushing the
///   now-arrived capital back out to each remote, actually-weighted
///   MultichainAdapter chain (see `record_request_tx`'s dev notes for exactly
///   which chains belong in that set). Keyed by the extrinsic's own
///   `chain_id` parameter (see `RequestChainEntry`), since a request can need
///   more than one such leg at once. `AdapterApplied` covers both directions
///   — `Supplied` for a deposit, `WithdrawRequested` for a redeem — since
///   both mean the same thing structurally: the Adapter has been notified and
///   acted on this leg. Not every chain in this set needs an
///   `AdapterBridgeExecuted` first: a chain that's *also* the origin vault's
///   own chain, or Hub, can self-fulfill its allocation synchronously (no
///   Bridge leg at all — the Adapter Contract call is local), so
///   `AdapterApplied` alone is valid for it. Such a chain may not even be in
///   `RequestAdapterChains` yet when its `AdapterApplied` evidence arrives —
///   see `Pallet::ensure_adapter_chain_declared`'s doc comment for why this
///   pallet self-declares it on first touch rather than requiring
///   `RequestQueued` to have already listed it.
///
/// `adapter_chain_ids` (the explicit parameter) is only ever supplied at
/// `RequestQueued` — never at `Requested`, regardless of Hub or Spoke — since
/// `RequestQueued` is precisely the step defined as "the Valuation Contract
/// has now decided the Adapter routing," for both vault locations alike. But
/// `RequestAdapterChains` itself (the actual stored set) can already contain
/// entries before `RequestQueued` ever runs, via the self-declare mechanism
/// above — `RequestQueued` merges its `adapter_chain_ids` into whatever's
/// already there rather than overwriting it.
///
/// `None` and `Completed` are read-only sentinels, never valid
/// `record_request_tx` input (rejected with `Error::InvalidRequestStep`).
/// Unlike `SettlementStep::Queued` (which `get_settlement` genuinely returns
/// for an untriggered settlement), `None` is never actually returned by
/// `get_request` either — `get_request` reverts outright for a request_id
/// that was never opened, so there's no "not yet requested" state to report —
/// it exists purely so `record_request_tx` has a well-defined way to reject
/// step `0` as invalid input, same as `Completed`. Named `None` rather than
/// `Queued` specifically to avoid sitting next to `RequestQueued` under a
/// near-identical name while meaning something completely different.
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum RequestStep {
	None,
	Requested,
	RequestBridgeExecuted,
	RequestQueued,
	AdapterBridgeExecuted,
	AdapterApplied,
	Completed,
}

/// 0 = redeem, 1 = deposit — mirrors interface.sol's `order_type` and
/// `pallet_tranche_investments::OrderType` exactly (same shape, declared
/// locally for the same no-hard-dependency reason as `RequestId` above).
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum OrderType {
	Redeem,
	Deposit,
}

/// Data supplied only when opening a fresh `RequestEntries` entry
/// (`record_request_tx` with `step == RequestStep::Requested`). Bundled into
/// one `Option` at the extrinsic boundary rather than four separate
/// `Option`s, so "provided" and "not provided" can't disagree field-by-field
/// — see `RequestEntry`'s doc comment for why `settlement_id` isn't here.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct RequestOpening {
	pub investor: H160,
	pub vault: VaultId,
	pub amount: U256,
	pub order_type: OrderType,
}

/// A request's registry entry. Keyed by `(product_id, request_id)` in storage
/// — `product_id` is still embedded here too (not just in the map key), same
/// convention as `pallet_tranche_investments::RequestedInvestment`, so a value
/// read out of storage carries enough context to act on independent of the key
/// it was fetched with.
///
/// `vault`/`investor`/`amount`/`order_type` are only known once the
/// `Requested` step is recorded, and stay fixed from then on. Mirrors most of
/// `pallet_tranche_investments::record_investment_request`'s parameter list
/// (its `product_id`/`request_id` are this entry's own storage keys instead
/// of fields) — `settlement_id` is deliberately NOT included: it isn't
/// actually knowable at request_tx time. It's assigned by the Valuation
/// Contract only once the request lands on the Hub and
/// `record_investment_request` runs; the Spoke-side bridge message itself
/// (Msg A / the redeem-request message) carries no settlement_id field for
/// the recorder to observe. So this entry gives investors/dashboards the
/// same request detail visibility during the request's own pipeline window
/// that only exists officially in `pallet-tranche-investments` from the
/// request's final leg onward — minus settlement_id, which isn't available
/// any earlier than that regardless.
///
/// Holds the Inbound leg's Bridge evidence (`bridge_tx`) directly rather than
/// per-chain, unlike the Adapter legs (`RequestChainEntries`) — a request
/// only ever has one vault, so at most one Inbound leg, always for that
/// vault's own chain. `bridge_tx` stays `None` forever for a Hub-vault
/// request (no Inbound leg applies — see `RequestStep`'s doc comment); unlike
/// `bridge_tx`, `queued_tx` is populated for **every** request regardless of
/// Hub or Spoke, since `RequestStep::RequestQueued` applies to both.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct RequestEntry<BlockNumber> {
	pub product_id: ProductId,
	/// The tranche vault this request targets.
	pub vault: VaultId,
	/// Investor address the entry was opened with.
	pub investor: H160,
	/// Investor's full requested amount (pre-allocation), same units as
	/// `record_investment_request`'s `amount`.
	pub amount: U256,
	pub order_type: OrderType,
	/// Evidence for the `Requested` step itself.
	pub request_tx: Option<TxRecord<BlockNumber>>,
	/// Inbound leg, Bridge phase (Spoke -> Hub). `None` forever if the vault is
	/// on Hub (no Inbound leg needed).
	pub bridge_tx: Option<TxRecord<BlockNumber>>,
	/// Evidence for `RequestStep::RequestQueued` — the moment this request's
	/// capital is confirmed at the Hub Valuation Contract and
	/// `adapter_chain_ids` becomes known. Populated for every request, Hub or
	/// Spoke alike (for a Hub-vault request this is typically the same
	/// `tx_hash` as `request_tx`, recorded via a separate call — see
	/// `RequestStep::RequestQueued`'s doc comment).
	pub queued_tx: Option<TxRecord<BlockNumber>>,
}

/// One chain's Adapter leg (Bridge+Applied) within a request — the Hub
/// Valuation Contract pushing capital out to one remote, weighted
/// MultichainAdapter chain. Keyed by `(product_id, request_id, chain_id)` in
/// storage — unlike interface.sol's `AdapterLeg`, `chain_id` itself is
/// NOT a field here, since it's already the storage map's own key. Mirrors
/// `SettlementChainEntry`, except an Adapter leg only ever has one
/// Bridge+Applied pair (there's no Collect/Response/Finalize subdivision on
/// the request side).
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
	Default,
)]
pub struct RequestChainEntry<BlockNumber> {
	pub bridge_tx: Option<TxRecord<BlockNumber>>,
	/// Evidence for `RequestStep::AdapterApplied` — the MultichainAdapter has
	/// been notified and acted on this leg (`Supplied` for a deposit,
	/// `WithdrawRequested` for a redeem).
	pub applied_tx: Option<TxRecord<BlockNumber>>,
}

// ---------------------------------------------------------------------------
// Settlement pipeline
// ---------------------------------------------------------------------------

/// Step within the settlement pipeline. Mirrors interface.sol's
/// `SettlementStep`. `Queued`/`Triggered`/`Settled` are the three states
/// `get_settlement`'s own `status` moves through —
/// `Queued` (not yet triggered), `Triggered` (triggered, awaiting
/// completion), `Settled` (every chain has reached *its own* terminal step —
/// `SettleApplied` if it's in `SettlementFinalizeChains`, otherwise
/// `NavReceived`, since a chain that's Collect/Response-only, i.e.
/// has an Adapter but no vault, never gets a Finalize leg to begin with — see
/// `record_settlement_tx`'s dev notes). The middle six describe one chain's
/// own progress instead — a Collect/Response/Finalize leg crossed with a
/// Bridge/Hooks phase, flattened into this same enum so a single `step`
/// parameter can select any of them. The three Bridge-phase values are
/// suffixed `Executed` (generic Socket-message evidence, nothing more
/// specific to name them after); the three Hooks-phase values are instead
/// named after the underlying Contract event each one's evidence actually
/// is — `NavReported` (TrancheManager, Collect leg), `NavReceived`
/// (Valuation, Response leg), `SettleApplied` (TrancheManager, Finalize
/// leg) — same event-name-mirroring convention as `RequestStep`'s
/// `RequestQueued`/`AdapterApplied`. `Queued` and `Settled` are read-only
/// sentinels and must never be accepted as `record_settlement_tx`'s
/// extrinsic input (rejected with `Error::InvalidSettlementStep`) — seven
/// recordable values in total (`Triggered` plus the six leg steps).
///
/// A settlement that needs no cross-chain action at all is represented by
/// `Triggered` with both `collect_response_chain_ids` and `finalize_chain_ids`
/// empty — no separate step value needed for this: `Triggered` no longer
/// requires either set to be non-empty (unlike an earlier version of this
/// pallet, which had one combined `spoke_chain_ids`), so both empty alone
/// unambiguously means "nothing to collect/respond/finalize" to every read
/// path via vacuous truth — `get_settlement` already reports this correctly
/// with no special-casing.
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum SettlementStep {
	Queued,
	Triggered,
	CollectBridgeExecuted,
	NavReported,
	ResponseBridgeExecuted,
	NavReceived,
	FinalizeBridgeExecuted,
	SettleApplied,
	Settled,
}

/// One spoke chain's full leg-by-leg registry entry within a
/// settlement. Keyed by `(product_id, settlement_id, spoke_chain_id)` in
/// storage — unlike interface.sol's `SettlementChainSteps`, `spoke_chain_id`
/// itself is NOT a field here, since it's already the storage map's own key
/// (no need to duplicate it into the value).
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
	Default,
)]
pub struct SettlementChainEntry<BlockNumber> {
	pub collect_bridge_tx: Option<TxRecord<BlockNumber>>,
	pub nav_reported_tx: Option<TxRecord<BlockNumber>>,
	pub response_bridge_tx: Option<TxRecord<BlockNumber>>,
	pub nav_received_tx: Option<TxRecord<BlockNumber>>,
	pub finalize_bridge_tx: Option<TxRecord<BlockNumber>>,
	pub settle_applied_tx: Option<TxRecord<BlockNumber>>,
}

// ---------------------------------------------------------------------------
// Receives
// ---------------------------------------------------------------------------

/// Which receivable pool a receive() tx drained (renamed from `ClaimKind`
/// 2026-08-06 — "Claim" as a term for this whole tracking pipeline was
/// replaced with "Receive" throughout; the underlying investor-facing
/// Solidity call being tracked is still literally named `receive()` on
/// TrancheVault, that's an external fact this rename doesn't change).
/// Mirrors interface.sol's `ReceiveKind` — TrancheManager pools receivable
/// amounts per (investor, vault), not per request_id, so redeem/deposit still
/// need distinguishing even though neither is tied to one specific request
/// anymore.
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum ReceiveKind {
	Redeem,
	Deposit,
}

/// One recorded receive() tx. Stored under `ReceiveEntries`' `(investor,
/// vault, tx_hash)` key. `investor` here is the *controller* (ERC-7540
/// terminology — the party whose depositRequest/redeemRequest this receive()
/// call settles, matching `RequestEntry::investor` and everything keyed by
/// "investor" elsewhere in this pallet, e.g.
/// `InvestorActiveRequests`/`InvestorRequestHistory`), not necessarily who the
/// funds went to — see `receiver` below. `vault` is part of the key alongside
/// `tx_hash` — unlike `request_id`/`settlement_id`, which are only unique
/// within their own `product_id` namespace, `tx_hash` alone is only unique
/// within its own *chain*, so `vault` (whose `chain_id` disambiguates it) has
/// to stay in the key to rule out two different chains coincidentally
/// producing the same hash. `product_id` is still not part of the key —
/// `VaultId` is already globally unique (enforced by pallet-tranche-system),
/// so keying on `product_id` too would be redundant. `investor`/`vault` are
/// both also duplicated into the value itself (fields below), same rationale
/// as `RequestEntry::product_id`: a value read out of storage carries enough
/// context to act on independent of the key it was fetched with.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct ReceiveEntry<BlockNumber> {
	/// The controller whose request this receive() call settles — same value
	/// as this entry's own storage key. ERC-7540 calls this the controller;
	/// named `investor` here to match every other "who does this belong to"
	/// field in this pallet.
	pub investor: H160,
	/// The tranche vault this receive() call was against — same value as this
	/// entry's own storage key.
	pub vault: VaultId,
	/// Who actually received the funds. TrancheManager's receive() call lets
	/// the controller (`investor` above) designate a different receiver;
	/// `receiver == investor` when the controller receives for themselves.
	pub receiver: H160,
	/// Shares received (`kind == Deposit`) or assets received (`kind == Redeem`).
	pub amount: U256,
	pub tx: TxRecord<BlockNumber>,
	pub kind: ReceiveKind,
}

// ---------------------------------------------------------------------------
// Whitelist pipeline
// ---------------------------------------------------------------------------

/// Opaque per-action nonce, generated by the Hub-chain Orchestrator contract
/// when it emits `WhitelistRequested` — the correlator that lets a recorder
/// tie one whitelist action's Trigger/Bridge/Applied tx together into a
/// single `WhitelistEntries` entry, the same role `request_id`/`settlement_id`
/// play for the Request/Settlement pipelines. Threaded through the CCCP
/// bridge message's own `variants` payload unchanged, and echoed back
/// verbatim by `WhitelistApplied` on the Spoke chain — never regenerated
/// mid-flight.
pub type WhitelistNonce = U256;

/// Step within a whitelist grant/revoke action's pipeline. Mirrors
/// interface.sol's `WhitelistStep`. Named after the underlying Contract event
/// wherever one exists 1:1 — `WhitelistRequested` (Orchestrator, Hub) and
/// `WhitelistApplied` (TrancheManager, Spoke) — same event-name-mirroring
/// convention as `RequestStep`/`SettlementStep`. `BridgeExecuted` is the
/// generic Bridge-phase Socket evidence in between, same as every other
/// pipeline's Bridge phase (nothing more specific to name it after).
///
/// Same Hub-vault/Spoke-vault branching as `RequestStep`: a whitelist action
/// always originates on Hub (a ProductAdmin's grant_permission/
/// revoke_permission call, routed through Orchestrator), but TrancheManager
/// (the contract that actually applies the grant/revoke) can live on Hub too
/// — a product with a Hub-deployed vault binds a Hub-chain TrancheManager
/// entry the same as any Spoke chain (see `pallet_tranche_system::
/// ProductDetails::multichain_tranche_managers`'s doc comment). So:
/// - Hub-vault action: `WhitelistApplied` follows `WhitelistRequested`
///   directly (no Bridge leg — `BridgeExecuted` reverts with
///   `Error::UnexpectedWhitelistBridgeLeg` if attempted, same rationale as
///   `RequestStep::RequestBridgeExecuted` reverting for a Hub-vault request).
/// - Spoke-vault action: all three steps, in order — `WhitelistApplied` only
///   reachable once `BridgeExecuted` has landed.
///
/// `None` is a read-only sentinel, never valid `record_whitelist_tx` input
/// (rejected with `Error::InvalidWhitelistStep`) — same rationale as
/// `RequestStep::None`: never actually returned by a read either, since a
/// whitelist action can't be looked up before `WhitelistRequested` opens its
/// entry.
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum WhitelistStep {
	None,
	WhitelistRequested,
	BridgeExecuted,
	WhitelistApplied,
}

/// One whitelist grant/revoke action's registry entry. Keyed by `(who, vault,
/// nonce)` in `WhitelistEntries` — `nonce` alone is likely already globally
/// unique (Orchestrator's own counter), but `who`/`vault` are kept in the key
/// too anyway, same defensive-specificity rationale as `ReceiveEntries`'
/// `(investor, vault, tx_hash)`, and to let a caller enumerate one account's
/// whitelist history via `iter_prefix(who)`. `product_id` is NOT part of the
/// key (same rationale as `ReceiveEntry` — `VaultId` is already globally
/// unique) but IS resolved once, at `WhitelistRequested` time, via
/// `T::Vaults::product_id_for_vault`, and stored here so a reader doesn't
/// need a second lookup.
#[derive(
	Clone,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub struct WhitelistEntry<BlockNumber> {
	/// Resolved from `vault` via `T::Vaults::product_id_for_vault` at
	/// `WhitelistRequested` time — not itself part of the storage key (see
	/// struct-level doc comment), but duplicated here so a value read out of
	/// storage carries enough context to act on independent of the key it
	/// was fetched with, same rationale as `RequestEntry::product_id`.
	pub product_id: ProductId,
	/// The tranche vault this whitelist action targets — same value as this
	/// entry's own storage key.
	pub vault: VaultId,
	/// The account whose whitelist status is being changed — same value as
	/// this entry's own storage key.
	pub who: H160,
	/// `true` = grant, `false` = revoke. Fixed for the lifetime of this
	/// entry — every step after `WhitelistRequested` must resupply the same
	/// value (checked, not just trusted) since Solidity has no `Option<bool>`
	/// to sentinel-gate it the way `RequestOpening`-style fields are gated.
	pub grant: bool,
	/// Evidence for `WhitelistStep::WhitelistRequested`.
	pub request_tx: Option<TxRecord<BlockNumber>>,
	/// Evidence for `WhitelistStep::BridgeExecuted`. `None` forever if `vault`
	/// is on Hub (no Bridge leg — see `WhitelistStep`'s doc comment).
	pub bridge_tx: Option<TxRecord<BlockNumber>>,
	/// Evidence for `WhitelistStep::WhitelistApplied`.
	pub applied_tx: Option<TxRecord<BlockNumber>>,
}

// ---------------------------------------------------------------------------
// Tx recorder origin
// ---------------------------------------------------------------------------

/// `EnsureOrigin` that accepts only a signed origin matching the account
/// currently stored in `TxRecorder`. Unlike
/// `pallet_tranche_investments::EnsureValuation` (which checks a
/// precompile-constructed custom `Origin` variant), this checks an ordinary
/// signed extrinsic directly against pallet storage — same pattern as
/// `pallet_tranche_permissions::grant_permission`'s `ProductAdmins` check, just
/// promoted to a reusable `EnsureOrigin` impl since every `record_*` extrinsic
/// needs the identical check.
/// Wire as `type RecorderOrigin = pallet_tranche_tx_registry::EnsureTxRecorder<Runtime>`
/// in the runtime — see `Config::RecorderOrigin`.
pub struct EnsureTxRecorder<T>(PhantomData<T>);

impl<OuterOrigin, T> frame_support::traits::EnsureOrigin<OuterOrigin> for EnsureTxRecorder<T>
where
	T: pallet::pallet::Config,
	OuterOrigin: Into<Result<frame_system::RawOrigin<T::AccountId>, OuterOrigin>>
		+ From<frame_system::RawOrigin<T::AccountId>>,
{
	type Success = T::AccountId;

	fn try_origin(o: OuterOrigin) -> Result<Self::Success, OuterOrigin> {
		o.into().and_then(|raw| match raw {
			frame_system::RawOrigin::Signed(who)
				if pallet::pallet::TxRecorder::<T>::get().as_ref() == Some(&who) =>
			{
				Ok(who)
			},
			raw => Err(OuterOrigin::from(raw)),
		})
	}

	#[cfg(feature = "runtime-benchmarks")]
	fn try_successful_origin() -> Result<OuterOrigin, ()> {
		let recorder = pallet::pallet::TxRecorder::<T>::get().ok_or(())?;
		Ok(OuterOrigin::from(frame_system::RawOrigin::Signed(recorder)))
	}
}
