global:
  scrape_interval: 3s
  evaluation_interval: 3s

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "substrate_node"
    scrape_interval: 3s
    static_configs:
      - targets: [ "host.docker.internal:9615" ]
  - job_name: "node_exporter"
    scrape_interval: 3s
    static_configs:
      - targets: [ "node-exporter:9100" ]
#  - job_name: "relayer"
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ "host.docker.internal:8000" ]
