// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_tranche_permissions_v2`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /Users/alexwon/workspace/pilab/bifrost/polkadot-sdk-patched/target/release/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/target/release/wbuild/bifrost-dev-runtime/bifrost_dev_runtime.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --allow-missing-host-functions
// --pallet
// pallet_tranche_permissions_v2
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --output
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/pallets/omnifi/v2/tranche-permissions/src/weights.rs
// --template
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_tranche_permissions_v2`.
pub trait WeightInfo {
	fn grant_permission() -> Weight;
	fn revoke_permission() -> Weight;
}

/// Weights for `pallet_tranche_permissions_v2` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TranchePermissionsV2::ProductAdmins` (r:1 w:0)
	/// Proof: `TranchePermissionsV2::ProductAdmins` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TranchePermissionsV2::TrancheInvestors` (r:1 w:1)
	/// Proof: `TranchePermissionsV2::TrancheInvestors` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn grant_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `3864`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(25_000_000, 3864)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TranchePermissionsV2::ProductAdmins` (r:1 w:0)
	/// Proof: `TranchePermissionsV2::ProductAdmins` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TranchePermissionsV2::TrancheInvestors` (r:1 w:1)
	/// Proof: `TranchePermissionsV2::TrancheInvestors` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn revoke_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `525`
		//  Estimated: `3990`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(28_000_000, 3990)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TranchePermissionsV2::ProductAdmins` (r:1 w:0)
	/// Proof: `TranchePermissionsV2::ProductAdmins` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TranchePermissionsV2::TrancheInvestors` (r:1 w:1)
	/// Proof: `TranchePermissionsV2::TrancheInvestors` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn grant_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `3864`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(25_000_000, 3864)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TranchePermissionsV2::ProductAdmins` (r:1 w:0)
	/// Proof: `TranchePermissionsV2::ProductAdmins` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TranchePermissionsV2::TrancheInvestors` (r:1 w:1)
	/// Proof: `TranchePermissionsV2::TrancheInvestors` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn revoke_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `525`
		//  Estimated: `3990`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(28_000_000, 3990)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
