// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_tranche_custom_flows`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /Users/alexwon/workspace/pilab/bifrost/polkadot-sdk-patched/target/release/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/target/release/wbuild/bifrost-dev-runtime/bifrost_dev_runtime.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --allow-missing-host-functions
// --pallet
// pallet_tranche_custom_flows
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --output
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/pallets/omnifi/tranche-custom-flows/src/weights.rs
// --template
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_tranche_custom_flows`.
pub trait WeightInfo {
	fn set_flow_descriptor(s: u32, ) -> Weight;
	fn record_flow_tx(s: u32, n: u32, m: u32, ) -> Weight;
}

/// Weights for `pallet_tranche_custom_flows` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TrancheCustomFlows::FlowDescriptors` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::FlowDescriptors` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 48]`.
	fn set_flow_descriptor(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `4644`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(10_378_414, 4644)
			// Standard Error: 1_456
			.saturating_add(Weight::from_parts(125_961, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:1 w:0)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::FlowDescriptors` (r:1 w:0)
	/// Proof: `TrancheCustomFlows::FlowDescriptors` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::FlowInstances` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::FlowInstances` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::FlowSlots` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::FlowSlots` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheCustomFlows::FlowLaneRecorded` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::FlowLaneRecorded` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::OpenInstanceCount` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::OpenInstanceCount` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::InvestorActiveFlows` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::InvestorActiveFlows` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheCustomFlows::InvestorFlowHistoryLen` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::InvestorFlowHistoryLen` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::InvestorFlowHistoryPage` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::InvestorFlowHistoryPage` (`max_values`: None, `max_size`: Some(4210), added: 6685, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 48]`.
	/// The range of component `n` is `[0, 30720]`.
	/// The range of component `m` is `[0, 30720]`.
	fn record_flow_tx(s: u32, n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308291 + s * (3 ±0)`
		//  Estimated: `311894 + s * (3 ±0)`
		// Minimum execution time: 200_000_000 picoseconds.
		Weight::from_parts(235_166_357, 311894)
			// Standard Error: 35
			.saturating_add(Weight::from_parts(291, 0).saturating_mul(n.into()))
			// Standard Error: 35
			.saturating_add(Weight::from_parts(236, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 3).saturating_mul(s.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TrancheCustomFlows::FlowDescriptors` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::FlowDescriptors` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 48]`.
	fn set_flow_descriptor(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `4644`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(10_378_414, 4644)
			// Standard Error: 1_456
			.saturating_add(Weight::from_parts(125_961, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:1 w:0)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::FlowDescriptors` (r:1 w:0)
	/// Proof: `TrancheCustomFlows::FlowDescriptors` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::FlowInstances` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::FlowInstances` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::FlowSlots` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::FlowSlots` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheCustomFlows::FlowLaneRecorded` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::FlowLaneRecorded` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::OpenInstanceCount` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::OpenInstanceCount` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::InvestorActiveFlows` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::InvestorActiveFlows` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheCustomFlows::InvestorFlowHistoryLen` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::InvestorFlowHistoryLen` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `TrancheCustomFlows::InvestorFlowHistoryPage` (r:1 w:1)
	/// Proof: `TrancheCustomFlows::InvestorFlowHistoryPage` (`max_values`: None, `max_size`: Some(4210), added: 6685, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 48]`.
	/// The range of component `n` is `[0, 30720]`.
	/// The range of component `m` is `[0, 30720]`.
	fn record_flow_tx(s: u32, n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308291 + s * (3 ±0)`
		//  Estimated: `311894 + s * (3 ±0)`
		// Minimum execution time: 200_000_000 picoseconds.
		Weight::from_parts(235_166_357, 311894)
			// Standard Error: 35
			.saturating_add(Weight::from_parts(291, 0).saturating_mul(n.into()))
			// Standard Error: 35
			.saturating_add(Weight::from_parts(236, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 3).saturating_mul(s.into()))
	}
}
