
//! Autogenerated weights for `pallet_btc_socket_queue`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.0
//! DATE: 2025-08-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmarker`, CPU: `AMD EPYC 7571`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./bifrost-node
// benchmark
// pallet
// --runtime
// ./bifrost_dev_runtime.compact.compressed.wasm
// --genesis-builder
// none
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// frame-weight-template.hbs
// --output
// weights.rs
// --hostname-override
// benchmarker
// --pallet
// pallet_btc_socket_queue

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_btc_socket_queue`.
pub trait WeightInfo {
	fn set_authority() -> Weight;
	fn set_socket() -> Weight;
	fn submit_unsigned_psbt() -> Weight;
	fn submit_signed_psbt() -> Weight;
	fn submit_executed_request() -> Weight;
	fn submit_rollback_request() -> Weight;
	fn submit_rollback_poll() -> Weight;
	fn submit_migration_request() -> Weight;
	fn set_max_fee_rate() -> Weight;
	fn submit_bump_fee_request() -> Weight;
	fn drop_pending_rollback_request() -> Weight;
}

/// Weights for `pallet_btc_socket_queue` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `BtcSocketQueue::Authority` (r:1 w:1)
	/// Proof: `BtcSocketQueue::Authority` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1505`
		// Minimum execution time: 17_380_000 picoseconds.
		Weight::from_parts(17_860_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BtcSocketQueue::Socket` (r:1 w:1)
	/// Proof: `BtcSocketQueue::Socket` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_socket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1505`
		// Minimum execution time: 17_631_000 picoseconds.
		Weight::from_parts(18_080_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Blaze::IsActivated` (r:1 w:0)
	/// Proof: `Blaze::IsActivated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:0)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::CurrentRound` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::SystemVault` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::SystemVault` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::Authority` (r:1 w:0)
	/// Proof: `BtcSocketQueue::Authority` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::Socket` (r:1 w:0)
	/// Proof: `BtcSocketQueue::Socket` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `System::Digest` (r:1 w:0)
	/// Proof: `System::Digest` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EVM::AccountCodes` (r:1 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::SocketMessages` (r:1 w:1)
	/// Proof: `BtcSocketQueue::SocketMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::RegistrationPool` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::RegistrationPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_unsigned_psbt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1247`
		//  Estimated: `4712`
		// Minimum execution time: 891_600_000 picoseconds.
		Weight::from_parts(928_280_000, 0)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:0 w:1)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::BondedOutboundTx` (r:0 w:1)
	/// Proof: `BtcSocketQueue::BondedOutboundTx` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_signed_psbt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2339`
		//  Estimated: `5804`
		// Minimum execution time: 5_373_442_000 picoseconds.
		Weight::from_parts(5_442_233_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:0 w:1)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_executed_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2989`
		//  Estimated: `6454`
		// Minimum execution time: 50_611_000 picoseconds.
		Weight::from_parts(51_871_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:0)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::BondedRollbackOutputs` (r:1 w:1)
	/// Proof: `BtcSocketQueue::BondedRollbackOutputs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::CurrentRound` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::RegistrationPool` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::RegistrationPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::Authority` (r:1 w:0)
	/// Proof: `BtcSocketQueue::Authority` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::BitcoinSocket` (r:1 w:0)
	/// Proof: `BtcSocketQueue::BitcoinSocket` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `System::Digest` (r:1 w:0)
	/// Proof: `System::Digest` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EVM::AccountCodes` (r:1 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::SystemVault` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::SystemVault` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blaze::IsActivated` (r:1 w:0)
	/// Proof: `Blaze::IsActivated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn submit_rollback_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1247`
		//  Estimated: `4712`
		// Minimum execution time: 799_490_000 picoseconds.
		Weight::from_parts(840_650_000, 0)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RelayManager::Majority` (r:1 w:0)
	/// Proof: `RelayManager::Majority` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:0 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_rollback_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1186`
		//  Estimated: `4651`
		// Minimum execution time: 59_891_000 picoseconds.
		Weight::from_parts(61_491_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:0)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::CurrentRound` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::SystemVault` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::SystemVault` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::OngoingVaultMigration` (r:1 w:1)
	/// Proof: `BtcRegistrationPool::OngoingVaultMigration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Blaze::Utxos` (r:1 w:0)
	/// Proof: `Blaze::Utxos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_migration_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `788`
		//  Estimated: `4253`
		// Minimum execution time: 705_328_000 picoseconds.
		Weight::from_parts(734_378_000, 0)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:1)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn set_max_fee_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1493`
		// Minimum execution time: 16_830_000 picoseconds.
		Weight::from_parts(17_380_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:2 w:1)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:0)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::CurrentRound` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::SystemVault` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::SystemVault` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blaze::IsActivated` (r:1 w:0)
	/// Proof: `Blaze::IsActivated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::SocketMessages` (r:0 w:1)
	/// Proof: `BtcSocketQueue::SocketMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::BondedOutboundTx` (r:0 w:1)
	/// Proof: `BtcSocketQueue::BondedOutboundTx` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_bump_fee_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3606`
		//  Estimated: `9546`
		// Minimum execution time: 1_690_929_000 picoseconds.
		Weight::from_parts(1_730_550_000, 0)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blaze::IsActivated` (r:1 w:0)
	/// Proof: `Blaze::IsActivated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn drop_pending_rollback_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1264`
		//  Estimated: `4729`
		// Minimum execution time: 34_121_000 picoseconds.
		Weight::from_parts(35_131_000, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `BtcSocketQueue::Authority` (r:1 w:1)
	/// Proof: `BtcSocketQueue::Authority` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1505`
		// Minimum execution time: 17_380_000 picoseconds.
		Weight::from_parts(17_860_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `BtcSocketQueue::Socket` (r:1 w:1)
	/// Proof: `BtcSocketQueue::Socket` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_socket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1505`
		// Minimum execution time: 17_631_000 picoseconds.
		Weight::from_parts(18_080_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Blaze::IsActivated` (r:1 w:0)
	/// Proof: `Blaze::IsActivated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:0)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::CurrentRound` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::SystemVault` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::SystemVault` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::Authority` (r:1 w:0)
	/// Proof: `BtcSocketQueue::Authority` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::Socket` (r:1 w:0)
	/// Proof: `BtcSocketQueue::Socket` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `System::Digest` (r:1 w:0)
	/// Proof: `System::Digest` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EVM::AccountCodes` (r:1 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::SocketMessages` (r:1 w:1)
	/// Proof: `BtcSocketQueue::SocketMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::RegistrationPool` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::RegistrationPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_unsigned_psbt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1247`
		//  Estimated: `4712`
		// Minimum execution time: 891_600_000 picoseconds.
		Weight::from_parts(928_280_000, 0)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:0 w:1)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::BondedOutboundTx` (r:0 w:1)
	/// Proof: `BtcSocketQueue::BondedOutboundTx` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_signed_psbt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2339`
		//  Estimated: `5804`
		// Minimum execution time: 5_373_442_000 picoseconds.
		Weight::from_parts(5_442_233_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:0 w:1)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_executed_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2989`
		//  Estimated: `6454`
		// Minimum execution time: 50_611_000 picoseconds.
		Weight::from_parts(51_871_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:0)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::BondedRollbackOutputs` (r:1 w:1)
	/// Proof: `BtcSocketQueue::BondedRollbackOutputs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::CurrentRound` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::RegistrationPool` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::RegistrationPool` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::Authority` (r:1 w:0)
	/// Proof: `BtcSocketQueue::Authority` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::BitcoinSocket` (r:1 w:0)
	/// Proof: `BtcSocketQueue::BitcoinSocket` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `System::Digest` (r:1 w:0)
	/// Proof: `System::Digest` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EVM::AccountCodes` (r:1 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::SystemVault` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::SystemVault` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blaze::IsActivated` (r:1 w:0)
	/// Proof: `Blaze::IsActivated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn submit_rollback_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1247`
		//  Estimated: `4712`
		// Minimum execution time: 799_490_000 picoseconds.
		Weight::from_parts(840_650_000, 0)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RelayManager::Majority` (r:1 w:0)
	/// Proof: `RelayManager::Majority` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:0 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_rollback_poll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1186`
		//  Estimated: `4651`
		// Minimum execution time: 59_891_000 picoseconds.
		Weight::from_parts(61_491_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:0)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::CurrentRound` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::SystemVault` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::SystemVault` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::OngoingVaultMigration` (r:1 w:1)
	/// Proof: `BtcRegistrationPool::OngoingVaultMigration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Blaze::Utxos` (r:1 w:0)
	/// Proof: `Blaze::Utxos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_migration_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `788`
		//  Estimated: `4253`
		// Minimum execution time: 705_328_000 picoseconds.
		Weight::from_parts(734_378_000, 0)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:1)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn set_max_fee_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1493`
		// Minimum execution time: 16_830_000 picoseconds.
		Weight::from_parts(17_380_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `BtcSocketQueue::ExecutedRequests` (r:2 w:1)
	/// Proof: `BtcSocketQueue::ExecutedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::MaxFeeRate` (r:1 w:0)
	/// Proof: `BtcSocketQueue::MaxFeeRate` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::CurrentRound` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BtcRegistrationPool::SystemVault` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::SystemVault` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::PendingRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::PendingRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::FinalizedRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::FinalizedRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:0)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blaze::IsActivated` (r:1 w:0)
	/// Proof: `Blaze::IsActivated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::SocketMessages` (r:0 w:1)
	/// Proof: `BtcSocketQueue::SocketMessages` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BtcSocketQueue::BondedOutboundTx` (r:0 w:1)
	/// Proof: `BtcSocketQueue::BondedOutboundTx` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_bump_fee_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3606`
		//  Estimated: `9546`
		// Minimum execution time: 1_690_929_000 picoseconds.
		Weight::from_parts(1_730_550_000, 0)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `BtcRegistrationPool::ServiceState` (r:1 w:0)
	/// Proof: `BtcRegistrationPool::ServiceState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BtcSocketQueue::RollbackRequests` (r:1 w:1)
	/// Proof: `BtcSocketQueue::RollbackRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Blaze::IsActivated` (r:1 w:0)
	/// Proof: `Blaze::IsActivated` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn drop_pending_rollback_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1264`
		//  Estimated: `4729`
		// Minimum execution time: 34_121_000 picoseconds.
		Weight::from_parts(35_131_000, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}