name: Documentation
description: Correction, suggestion, anything related to BIFROST Network documentation
labels: ["Documentation"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: What would you like to say about BIFROST Network documentation?
      description: Missing/wrong information? Dead/incorrect links? Feedback?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Examples/References
      description: Do you have any examples or references regarding this?
