//! Autogenerated weights for pallet_bifrost_evm_tx_payment
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0
//! DO NOT EDIT THIS FILE MANUALLY!

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_bifrost_evm_tx_payment.
pub trait WeightInfo {
	fn add_fee_token() -> Weight;
	fn remove_fee_token() -> Weight;
	fn update_fee_token() -> Weight;
	fn set_user_fee_token() -> Weight;
	fn set_native_oracle() -> Weight;
	fn withdraw_collected_fees() -> Weight;
}

/// Weights for pallet_bifrost_evm_tx_payment using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: AcceptedFeeTokens (r:1 w:1)
	fn add_fee_token() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: AcceptedFeeTokens (r:1 w:1)
	fn remove_fee_token() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: AcceptedFeeTokens (r:1 w:1)
	fn update_fee_token() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: AcceptedFeeTokens (r:1 w:0)
	/// Storage: UserFeeToken (r:0 w:1)
	fn set_user_fee_token() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: NativeTokenOracle (r:0 w:1)
	/// Storage: NativeOracleDecimals (r:0 w:1)
	fn set_native_oracle() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// EVM call to transfer ERC20 tokens
	fn withdraw_collected_fees() -> Weight {
		// EVM call weight is higher due to ERC20 transfer execution
		Weight::from_parts(100_000_000, 0)
	}
}

impl WeightInfo for () {
	fn add_fee_token() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn remove_fee_token() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn update_fee_token() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn set_user_fee_token() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn set_native_oracle() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2))
	}

	fn withdraw_collected_fees() -> Weight {
		Weight::from_parts(100_000_000, 0)
	}
}
