[package]
name = "bifrost-testnet-constants"
version = "1.0.0"
description = "The runtime constants for Bifrost testnet"
authors = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
# Bifrost
bifrost-common-constants = { workspace = true }
bp-core = { workspace = true }

# Substrate
sp-core = { workspace = true }
frame-support = { workspace = true }
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }

[features]
default = ["std"]
std = ["pallet-evm/std", "sp-core/std", "frame-support/std"]
