// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_tranche_investments_v2`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /Users/alexwon/workspace/pilab/bifrost/polkadot-sdk-patched/target/release/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/target/release/wbuild/bifrost-dev-runtime/bifrost_dev_runtime.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --allow-missing-host-functions
// --pallet
// pallet_tranche_investments_v2
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --output
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/pallets/omnifi/v2/tranche-investments/src/weights.rs
// --template
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_tranche_investments_v2`.
pub trait WeightInfo {
	fn record_investment_request() -> Weight;
	fn record_investment_approval() -> Weight;
	fn record_investment_approvals(n: u32, ) -> Weight;
	fn record_adapter_valuations() -> Weight;
	fn record_settlement() -> Weight;
}

/// Weights for `pallet_tranche_investments_v2` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::RequestedInvestments` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::RequestedInvestments` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::ApprovedInvestments` (r:1 w:0)
	/// Proof: `TrancheInvestmentsV2::ApprovedInvestments` (`max_values`: None, `max_size`: Some(882), added: 3357, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn record_investment_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `334`
		//  Estimated: `4347`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 4347)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheInvestmentsV2::RequestedInvestments` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::RequestedInvestments` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:0)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::SettlementRequests` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::SettlementRequests` (`max_values`: None, `max_size`: Some(32074), added: 34549, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::ApprovedInvestments` (r:0 w:1)
	/// Proof: `TrancheInvestmentsV2::ApprovedInvestments` (`max_values`: None, `max_size`: Some(882), added: 3357, mode: `MaxEncodedLen`)
	fn record_investment_approval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1121`
		//  Estimated: `35539`
		// Minimum execution time: 59_000_000 picoseconds.
		Weight::from_parts(66_000_000, 35539)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TrancheInvestmentsV2::SettlementRequests` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::SettlementRequests` (`max_values`: None, `max_size`: Some(32074), added: 34549, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::RequestedInvestments` (r:999 w:999)
	/// Proof: `TrancheInvestmentsV2::RequestedInvestments` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:1 w:0)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::ApprovedInvestments` (r:0 w:999)
	/// Proof: `TrancheInvestmentsV2::ApprovedInvestments` (`max_values`: None, `max_size`: Some(882), added: 3357, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 1000]`.
	fn record_investment_approvals(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418 + n * (189 ±0)`
		//  Estimated: `35539 + n * (2680 ±0)`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(27_000_000, 35539)
			// Standard Error: 17_136
			.saturating_add(Weight::from_parts(16_148_477, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2680).saturating_mul(n.into()))
	}
	/// Storage: `TrancheInvestmentsV2::AdapterValuations` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::AdapterValuations` (`max_values`: None, `max_size`: Some(244174), added: 246649, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:100 w:0)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn record_adapter_valuations() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5890`
		//  Estimated: `253690`
		// Minimum execution time: 1_404_000_000 picoseconds.
		Weight::from_parts(1_557_000_000, 253690)
			.saturating_add(T::DbWeight::get().reads(101_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheInvestmentsV2::Settlements` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::Settlements` (`max_values`: None, `max_size`: Some(15718), added: 18193, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:100 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::LastSettlementId` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::LastSettlementId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::ProductNavs` (r:0 w:1)
	/// Proof: `TrancheInvestmentsV2::ProductNavs` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn record_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6137`
		//  Estimated: `253790`
		// Minimum execution time: 437_000_000 picoseconds.
		Weight::from_parts(455_000_000, 253790)
			.saturating_add(T::DbWeight::get().reads(103_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::RequestedInvestments` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::RequestedInvestments` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::ApprovedInvestments` (r:1 w:0)
	/// Proof: `TrancheInvestmentsV2::ApprovedInvestments` (`max_values`: None, `max_size`: Some(882), added: 3357, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn record_investment_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `334`
		//  Estimated: `4347`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 4347)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheInvestmentsV2::RequestedInvestments` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::RequestedInvestments` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:10 w:0)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::SettlementRequests` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::SettlementRequests` (`max_values`: None, `max_size`: Some(32074), added: 34549, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::ApprovedInvestments` (r:0 w:1)
	/// Proof: `TrancheInvestmentsV2::ApprovedInvestments` (`max_values`: None, `max_size`: Some(882), added: 3357, mode: `MaxEncodedLen`)
	fn record_investment_approval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1121`
		//  Estimated: `35539`
		// Minimum execution time: 59_000_000 picoseconds.
		Weight::from_parts(66_000_000, 35539)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TrancheInvestmentsV2::SettlementRequests` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::SettlementRequests` (`max_values`: None, `max_size`: Some(32074), added: 34549, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::RequestedInvestments` (r:999 w:999)
	/// Proof: `TrancheInvestmentsV2::RequestedInvestments` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::MultichainAdapterIndex` (r:1 w:0)
	/// Proof: `TrancheSystem::MultichainAdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::ApprovedInvestments` (r:0 w:999)
	/// Proof: `TrancheInvestmentsV2::ApprovedInvestments` (`max_values`: None, `max_size`: Some(882), added: 3357, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 1000]`.
	fn record_investment_approvals(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418 + n * (189 ±0)`
		//  Estimated: `35539 + n * (2680 ±0)`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(27_000_000, 35539)
			// Standard Error: 17_136
			.saturating_add(Weight::from_parts(16_148_477, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2680).saturating_mul(n.into()))
	}
	/// Storage: `TrancheInvestmentsV2::AdapterValuations` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::AdapterValuations` (`max_values`: None, `max_size`: Some(244174), added: 246649, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::AdapterIndex` (r:100 w:0)
	/// Proof: `TrancheSystem::AdapterIndex` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn record_adapter_valuations() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5890`
		//  Estimated: `253690`
		// Minimum execution time: 1_404_000_000 picoseconds.
		Weight::from_parts(1_557_000_000, 253690)
			.saturating_add(RocksDbWeight::get().reads(101_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheInvestmentsV2::Settlements` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::Settlements` (`max_values`: None, `max_size`: Some(15718), added: 18193, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:100 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::LastSettlementId` (r:1 w:1)
	/// Proof: `TrancheInvestmentsV2::LastSettlementId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TrancheInvestmentsV2::ProductNavs` (r:0 w:1)
	/// Proof: `TrancheInvestmentsV2::ProductNavs` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn record_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6137`
		//  Estimated: `253790`
		// Minimum execution time: 437_000_000 picoseconds.
		Weight::from_parts(455_000_000, 253790)
			.saturating_add(RocksDbWeight::get().reads(103_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
