#![cfg_attr(not(feature = "std"), no_std)]

mod pallet;
pub mod weights;

pub use pallet::pallet::*;
pub use weights::WeightInfo;

use pallet_rwa_pools::{EpochId, PoolId};
use parity_scale_codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use sp_core::U256;
use sp_runtime::RuntimeDebug;

// ---------------------------------------------------------------------------
// Storage types
// ---------------------------------------------------------------------------

/// Snapshot of cumulative off-chain net P&L (profit and loss) for a pool, as submitted by the
/// oracle feeder.
///
/// `cumulative_pnl` is the magnitude of the net P&L generated by the institution since pool
/// inception, signed via `is_loss`. It is submitted by the oracle feeder and does NOT include
/// repaid interest — that deduction is handled on-chain by `pallet-pools`.
///
/// `updated_block` records when the last submission occurred, allowing consumers to detect
/// stale NAV data.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct PnlEntry {
	/// Magnitude of the net cumulative P&L since pool inception, i.e. `|cumulative P&L|`.
	/// pallet-pools computes:
	/// oracle_nav = total_borrowed ± cumulative_pnl − repaid_earnings, floored at 0
	/// (subtracted when `is_loss`, added otherwise).
	pub cumulative_pnl: U256,
	/// `true` if `cumulative_pnl` represents a net loss; `false` for a net gain.
	/// Always `false` when `cumulative_pnl == 0` — zero is never signed.
	pub is_loss: bool,
	/// Block number at which this entry was last updated.
	pub updated_block: u32,
}
