#![cfg_attr(not(feature = "std"), no_std)]

mod pallet;
pub mod weights;

pub use pallet::pallet::*;
pub use weights::WeightInfo;

use pallet_rwa_pools::{EpochId, PoolId};
use parity_scale_codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use sp_core::U256;
use sp_runtime::RuntimeDebug;

// ---------------------------------------------------------------------------
// Storage types
// ---------------------------------------------------------------------------

/// Snapshot of cumulative off-chain earnings for a pool, as submitted by the oracle feeder.
///
/// `cumulative_earnings` is the monotonically increasing total earnings generated by the
/// institution since pool inception. It is submitted by the oracle feeder and does NOT
/// include repaid interest — that deduction is handled on-chain by `pallet-pools`.
///
/// `updated_block` records when the last submission occurred, allowing consumers to detect
/// stale NAV data.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct EarningsEntry {
	/// Cumulative total off-chain earnings (monotonically increasing).
	/// pallet-pools computes: oracle_nav = total_borrowed + (cumulative_earnings − repaid_earnings)
	pub cumulative_earnings: U256,
	/// Block number at which this entry was last updated.
	pub updated_block: u32,
}
