// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_tranche_tx_registry_v2`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /Users/alexwon/workspace/pilab/bifrost/polkadot-sdk-patched/target/release/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/target/release/wbuild/bifrost-dev-runtime/bifrost_dev_runtime.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --allow-missing-host-functions
// --pallet
// pallet_tranche_tx_registry_v2
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --output
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/pallets/omnifi/v2/tranche-tx-registry/src/weights.rs
// --template
// /Users/alexwon/workspace/pilab/bifrost/bifrost-node/scripts/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_tranche_tx_registry_v2`.
pub trait WeightInfo {
	fn set_tx_recorder() -> Weight;
	fn record_request_tx() -> Weight;
	fn record_settlement_tx(n: u32, ) -> Weight;
	fn record_receive_tx() -> Weight;
	fn record_whitelist_tx() -> Weight;
}

/// Weights for `pallet_tranche_tx_registry_v2` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TrancheTxRegistryV2::TxRecorder` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_tx_recorder() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `1505`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_000_000, 1505)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::RequestEntries` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::RequestEntries` (`max_values`: None, `max_size`: Some(826), added: 3301, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::InvestorActiveRequests` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorActiveRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheTxRegistryV2::InvestorRequestHistoryLen` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorRequestHistoryLen` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::InvestorRequestHistoryPage` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorRequestHistoryPage` (`max_values`: None, `max_size`: Some(4178), added: 6653, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:0 w:1)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn record_request_tx() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `330`
		//  Estimated: `7643`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(35_000_000, 7643)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `TrancheTxRegistryV2::RequestEntries` (r:999 w:999)
	/// Proof: `TrancheTxRegistryV2::RequestEntries` (`max_values`: None, `max_size`: Some(826), added: 3301, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::SettlementRequests` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::SettlementRequests` (`max_values`: None, `max_size`: Some(32074), added: 34549, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheTxRegistryV2::SettlementTriggers` (r:1 w:0)
	/// Proof: `TrancheTxRegistryV2::SettlementTriggers` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::SettlementChainEntries` (r:1 w:0)
	/// Proof: `TrancheTxRegistryV2::SettlementChainEntries` (`max_values`: None, `max_size`: Some(15115), added: 17590, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:0 w:1)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 1000]`.
	fn record_settlement_tx(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `440 + n * (196 ±0)`
		//  Estimated: `35539 + n * (3301 ±0)`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(33_000_000, 35539)
			// Standard Error: 7_308
			.saturating_add(Weight::from_parts(14_535_697, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3301).saturating_mul(n.into()))
	}
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::ReceiveEntries` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::ReceiveEntries` (`max_values`: None, `max_size`: Some(273), added: 2748, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::InvestorReceiveHistoryLen` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorReceiveHistoryLen` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::InvestorReceiveHistoryPage` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorReceiveHistoryPage` (`max_values`: None, `max_size`: Some(7762), added: 10237, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:0 w:1)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn record_receive_tx() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `330`
		//  Estimated: `11227`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(33_000_000, 11227)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TrancheTxRegistryV2::WhitelistEntries` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::WhitelistEntries` (`max_values`: None, `max_size`: Some(726), added: 3201, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheTxRegistryV2::LatestWhitelistNonce` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::LatestWhitelistNonce` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:0 w:1)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn record_whitelist_tx() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `330`
		//  Estimated: `4191`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(30_000_000, 4191)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TrancheTxRegistryV2::TxRecorder` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_tx_recorder() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `1505`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_000_000, 1505)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::RequestEntries` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::RequestEntries` (`max_values`: None, `max_size`: Some(826), added: 3301, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::InvestorActiveRequests` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorActiveRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheTxRegistryV2::InvestorRequestHistoryLen` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorRequestHistoryLen` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::InvestorRequestHistoryPage` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorRequestHistoryPage` (`max_values`: None, `max_size`: Some(4178), added: 6653, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:0 w:1)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn record_request_tx() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `330`
		//  Estimated: `7643`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(35_000_000, 7643)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `TrancheTxRegistryV2::RequestEntries` (r:999 w:999)
	/// Proof: `TrancheTxRegistryV2::RequestEntries` (`max_values`: None, `max_size`: Some(826), added: 3301, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::SettlementRequests` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::SettlementRequests` (`max_values`: None, `max_size`: Some(32074), added: 34549, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheTxRegistryV2::SettlementTriggers` (r:1 w:0)
	/// Proof: `TrancheTxRegistryV2::SettlementTriggers` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::SettlementChainEntries` (r:1 w:0)
	/// Proof: `TrancheTxRegistryV2::SettlementChainEntries` (`max_values`: None, `max_size`: Some(15115), added: 17590, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:0 w:1)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 1000]`.
	fn record_settlement_tx(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `440 + n * (196 ±0)`
		//  Estimated: `35539 + n * (3301 ±0)`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(33_000_000, 35539)
			// Standard Error: 7_308
			.saturating_add(Weight::from_parts(14_535_697, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3301).saturating_mul(n.into()))
	}
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::ReceiveEntries` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::ReceiveEntries` (`max_values`: None, `max_size`: Some(273), added: 2748, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::InvestorReceiveHistoryLen` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorReceiveHistoryLen` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistryV2::InvestorReceiveHistoryPage` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::InvestorReceiveHistoryPage` (`max_values`: None, `max_size`: Some(7762), added: 10237, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:0 w:1)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn record_receive_tx() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `330`
		//  Estimated: `11227`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(33_000_000, 11227)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TrancheTxRegistryV2::WhitelistEntries` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::WhitelistEntries` (`max_values`: None, `max_size`: Some(726), added: 3201, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Vaults` (r:1 w:0)
	/// Proof: `TrancheSystem::Vaults` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `TrancheSystem::Products` (r:1 w:0)
	/// Proof: `TrancheSystem::Products` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TrancheTxRegistryV2::LatestWhitelistNonce` (r:1 w:1)
	/// Proof: `TrancheTxRegistryV2::LatestWhitelistNonce` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `TrancheTxRegistry::TxRecorder` (r:0 w:1)
	/// Proof: `TrancheTxRegistry::TxRecorder` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn record_whitelist_tx() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `330`
		//  Estimated: `4191`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(30_000_000, 4191)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
