[package]
name = "precompile-utils-macro"
version = "1.0.0"
description = "Utility macros for precompile development"
authors = ["bifrost-platform"]
homepage = "https://thebifrost.io"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/bifrost-platform/bifrost-node"

[lib]
proc-macro = true

[dependencies]
case = "1.0"
num_enum = { version = "0.5.3", default-features = false }
prettyplease = "0.1.18"
proc-macro2 = "1.0"
quote = "1.0"
sha3 = "0.10"
syn = { version = "1.0", features = [ "extra-traits", "fold", "full", "visit" ] }
