#![cfg_attr(not(feature = "std"), no_std)]

mod pallet;

pub use pallet::pallet::*;

use pallet_tranche_system::{AdapterKey, ProductId, VaultId};
use parity_scale_codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use sp_core::{ConstU32, H160, U256};
use sp_runtime::{BoundedVec, RuntimeDebug};

// ---------------------------------------------------------------------------
// Primitive type aliases / constants
// ---------------------------------------------------------------------------

/// Opaque request identifier, generated by the Valuation Contract — this pallet
/// never generates its own.
pub type RequestId = U256;

/// Opaque settlement-cycle identifier, generated by the Valuation Contract.
pub type SettlementId = U256;

/// Maximum number of Adapter allocations a single investment can be split across.
/// Matches pallet-tranche-system's `MAX_MULTICHAIN_ADAPTERS` — an investment can't
/// be allocated across more MultichainAdapters than a product actually has.
pub const MAX_ALLOCATIONS: u32 = pallet_tranche_system::MAX_MULTICHAIN_ADAPTERS;

/// Maximum number of NAV info entries recorded per settlement.
pub const MAX_NAV_INFOS: u32 = pallet_tranche_system::MAX_MULTICHAIN_ADAPTERS;

/// Maximum byte length of a single NAV info entry's payload (after the leading
/// `structure_type` discriminant byte is stripped out into its own field).
/// The only currently-known layout — `timestamp (32B) + adapter (20B) + epoch_id
/// (32B)` = 84 bytes — fits comfortably; sized up for headroom on future
/// structure_types.
pub const MAX_NAV_INFO_LEN: u32 = 128;

// ---------------------------------------------------------------------------
// OrderType
// ---------------------------------------------------------------------------

/// Mirrors interface.sol's `order_type` (0 = Redeem, 1 = Deposit) — declaration
/// order here matches those values, though the precompile boundary converts
/// explicitly rather than relying on that.
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum OrderType {
	Redeem,
	Deposit,
}

// ---------------------------------------------------------------------------
// RequestedInvestment
// ---------------------------------------------------------------------------

/// A deposit/redeem request as recorded the moment it reaches the Valuation
/// Contract, before any Adapter allocation has happened.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct RequestedInvestment {
	pub product_id: ProductId,
	/// Valuation Contract's settlement cycle in effect at request time. Can
	/// differ from the eventual approval's settlement_id if the request isn't
	/// approved within the same window it arrived in.
	pub settlement_id: SettlementId,
	pub vault: VaultId,
	pub investor_address: H160,
	/// Investor's full requested amount (18-decimal), pre-allocation.
	pub amount: U256,
	pub order_type: OrderType,
}

// ---------------------------------------------------------------------------
// Allocation / ApprovedInvestment
// ---------------------------------------------------------------------------

/// One slice of an approved request: `amount` was allocated to the
/// MultichainAdapter identified by `adapter`.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct Allocation {
	pub adapter: AdapterKey,
	pub amount: U256,
}

/// A request's full approval. Embeds the original `RequestedInvestment` in
/// full (rather than a differently-shaped record) so that moving a request
/// from `RequestedInvestments` to `ApprovedInvestments` loses no information —
/// `vault`, `investor_address`, the original `amount`, `order_type`, and the
/// request-time `settlement_id` all remain reachable via `requested`.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct ApprovedInvestment {
	pub requested: RequestedInvestment,
	/// Valuation Contract's settlement cycle at approval time — distinct from
	/// `requested.settlement_id` (see that field's doc comment).
	pub settlement_id: SettlementId,
	/// Per-Adapter allocation breakdown; sum of `amount` across entries is
	/// expected to equal `requested.amount`.
	pub allocations: BoundedVec<Allocation, ConstU32<MAX_ALLOCATIONS>>,
	/// Finalized claimable amount for the investor — minted share-token amount
	/// for a Deposit request, or released underlying-asset amount for a Redeem
	/// request, per `requested.order_type`.
	pub claimable_assets: U256,
}

// ---------------------------------------------------------------------------
// NavInfo
// ---------------------------------------------------------------------------

/// One entry of a settlement's `nav_infos[]`, as recorded by
/// `record_settlement_info`. `structure_type` is the leading discriminant byte
/// from interface.sol's packed encoding; `payload` is the raw remainder,
/// undecoded — decoders must branch on `structure_type` before interpreting it.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct NavInfo {
	pub structure_type: u8,
	pub payload: BoundedVec<u8, ConstU32<MAX_NAV_INFO_LEN>>,
}
