#![cfg_attr(not(feature = "std"), no_std)]

mod pallet;
pub mod weights;

pub use pallet::pallet::*;
pub use weights::WeightInfo;

use pallet_tranche_system::{AdapterKey, ProductId, VaultId};
use parity_scale_codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use sp_core::{ConstU32, H160, U256};
use sp_runtime::{BoundedVec, RuntimeDebug};
use sp_std::marker::PhantomData;

// ---------------------------------------------------------------------------
// Primitive type aliases / constants
// ---------------------------------------------------------------------------

/// Opaque request identifier, generated by the Valuation Contract — this pallet
/// never generates its own.
pub type RequestId = U256;

/// Opaque settlement-cycle identifier, generated by the Valuation Contract.
pub type SettlementId = U256;

/// Maximum number of Adapter allocations a single investment can be split across.
/// Matches pallet-tranche-system's `MAX_MULTICHAIN_ADAPTERS` — an investment can't
/// be allocated across more MultichainAdapters than a product actually has.
pub const MAX_ALLOCATIONS: u32 = pallet_tranche_system::MAX_MULTICHAIN_ADAPTERS;

/// Maximum number of Adapter valuation entries recorded per settlement — one
/// entry per Adapter, so bounded the same way as `MAX_ALLOCATIONS`.
pub const MAX_ADAPTER_VALUATIONS: u32 = pallet_tranche_system::MAX_MULTICHAIN_ADAPTERS;

/// Maximum number of `AssetPosition` entries per `AdapterValuation`. No
/// equivalent bound exists elsewhere in this pallet family — an Adapter's
/// underlying holdings aren't a registered, product-scoped concept the way
/// tranches/adapters/collaterals are, so this is a fresh cap sized in the same
/// ballpark as other per-entity bounds (e.g. `MAX_COLLATERALS`).
pub const MAX_ASSET_POSITIONS: u32 = 20;

// ---------------------------------------------------------------------------
// OrderType
// ---------------------------------------------------------------------------

/// Mirrors interface.sol's `order_type` (0 = Redeem, 1 = Deposit) — declaration
/// order here matches those values, though the precompile boundary converts
/// explicitly rather than relying on that.
#[derive(
	Clone,
	Copy,
	Encode,
	Decode,
	DecodeWithMemTracking,
	PartialEq,
	Eq,
	RuntimeDebug,
	TypeInfo,
	MaxEncodedLen,
)]
pub enum OrderType {
	Redeem,
	Deposit,
}

// ---------------------------------------------------------------------------
// RequestedInvestment
// ---------------------------------------------------------------------------

/// A deposit/redeem request as recorded the moment it reaches the Valuation
/// Contract, before any Adapter allocation has happened.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct RequestedInvestment {
	pub product_id: ProductId,
	/// Valuation Contract's settlement cycle in effect at request time. Can
	/// differ from the eventual approval's settlement_id if the request isn't
	/// approved within the same window it arrived in.
	pub settlement_id: SettlementId,
	pub vault: VaultId,
	pub investor_address: H160,
	/// Investor's full requested amount (18-decimal), pre-allocation.
	pub amount: U256,
	pub order_type: OrderType,
}

// ---------------------------------------------------------------------------
// Allocation / ApprovedInvestment
// ---------------------------------------------------------------------------

/// One slice of an approved request: `amount` was allocated to the
/// MultichainAdapter identified by `adapter`.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct Allocation {
	pub adapter: AdapterKey,
	pub amount: U256,
}

/// A request's full approval. Embeds the original `RequestedInvestment` in
/// full (rather than a differently-shaped record) so that moving a request
/// from `RequestedInvestments` to `ApprovedInvestments` loses no information —
/// `vault`, `investor_address`, the original `amount`, `order_type`, and the
/// request-time `settlement_id` all remain reachable via `requested`.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct ApprovedInvestment {
	pub requested: RequestedInvestment,
	/// Valuation Contract's settlement cycle at approval time — distinct from
	/// `requested.settlement_id` (see that field's doc comment).
	pub settlement_id: SettlementId,
	/// Per-Adapter allocation breakdown; sum of `amount` across entries is
	/// expected to equal `requested.amount`.
	pub allocations: BoundedVec<Allocation, ConstU32<MAX_ALLOCATIONS>>,
	/// Finalized claimable amount for the investor — minted share-token amount
	/// for a Deposit request, or released underlying-asset amount for a Redeem
	/// request, per `requested.order_type`.
	pub claimable_assets: U256,
}

// ---------------------------------------------------------------------------
// AdapterValuation / AssetPosition
// ---------------------------------------------------------------------------

/// One entry of a settlement's Adapter NAV breakdown, as recorded by
/// `record_adapter_valuations`. Field names/shape mirror interface.sol's
/// `AdapterValuation` 1:1 (itself mirroring the node's own base valuation
/// record format) rather than this pallet's usual snake_case — see that
/// struct's doc comment.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct AdapterValuation {
	/// EVM chain ID the adapter lives on — combined with `adapter`, this is
	/// the adapter's global identity, mirroring `AdapterKey`'s shape (kept as
	/// a bare pair here rather than reusing `AdapterKey` directly, since this
	/// struct's field names/casing intentionally follow interface.sol's
	/// `AdapterValuation`, not pallet-tranche-system's convention).
	pub chain_id: u64,
	pub adapter: H160,
	/// Adapter's own local epoch/settlement counter.
	pub epoch_id: U256,
	/// Timestamp this valuation was struck as-of.
	pub valuation_cutoff: u64,
	/// Cumulative principal deployed into this adapter.
	pub principal: U256,
	pub positions: BoundedVec<AssetPosition, ConstU32<MAX_ASSET_POSITIONS>>,
}

/// One asset held by an Adapter as of its valuation cutoff.
#[derive(
	Clone, Encode, Decode, DecodeWithMemTracking, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen,
)]
pub struct AssetPosition {
	/// Asset's token address on the parent `AdapterValuation`'s `chain_id`
	/// (native to that chain, not a Hub address).
	pub asset: H160,
	/// Held amount, in `asset`'s own decimals.
	pub amount: U256,
	/// Price at valuation time, FixedU128-style 1e18 fixed-point (sourced
	/// from the Adapter's own NAV oracle, not this pallet).
	pub price_usd: U256,
	/// `amount * price_usd`, recorded alongside `amount`/`price_usd` rather
	/// than only stored, so downstream consumers can re-derive and
	/// cross-check it without re-fetching price data. Not verified against
	/// `amount * price_usd` by this pallet — Valuation is trusted for it,
	/// same as every other value in this interface.
	pub usd_value: U256,
	/// Whether this position counts toward the adapter's NAV — pre-swap
	/// reward tokens are `false` (see design doc §4).
	pub counted: bool,
}

// ---------------------------------------------------------------------------
// Valuation origin
// ---------------------------------------------------------------------------

/// `EnsureOrigin` that accepts only the `Origin::Valuation` pallet origin —
/// mirrors pallet-tranche-system's `EnsureProductAdmin`, except `Origin::Valuation`
/// carries no payload (the precompile already resolved and verified the caller
/// against the product's registered `valuation_address` before constructing this
/// origin, so there's nothing left to hand back as `Success`).
/// Wire as `type ValuationOrigin = pallet_tranche_investments::EnsureValuation<Runtime>`
/// in the runtime.
pub struct EnsureValuation<T>(PhantomData<T>);

impl<OuterOrigin, T> frame_support::traits::EnsureOrigin<OuterOrigin> for EnsureValuation<T>
where
	T: Config,
	OuterOrigin: Into<Result<Origin, OuterOrigin>> + From<Origin>,
{
	type Success = ();
	fn try_origin(o: OuterOrigin) -> Result<Self::Success, OuterOrigin> {
		match o.into() {
			Ok(Origin::Valuation) => Ok(()),
			Err(o) => Err(o),
		}
	}

	#[cfg(feature = "runtime-benchmarks")]
	fn try_successful_origin() -> Result<OuterOrigin, ()> {
		Ok(OuterOrigin::from(Origin::Valuation))
	}
}
